### ISSUE TITLE
Unnecessary files on transitive nuget installation

### ISSUE THREAD

**Issue by mikebridge** [google/protobuf#1037]
I installed a package which has a transitive dependency on Google.ProtocolBuffers.  I was surprised to see that nuget put several folders of tutorials, license files, changelogs and all sorts of other unnecessary files in the root of every project I installed it in.  These are all available in `/packages` if anyone needs them, and shouldn't be copied into projects.

**Comment by jskeet** [comment]
Sorry for not seeing this question before. Do you see the same issue when installing it as a *direct* dependency?

I've just tried with 3.0.0-beta2 and not seen this with either direct or indirect dependencies. Perhaps this was fixed in beta2? Also check that you're using `Google.Protobuf` (the package for this project) rather than `Google.ProtocolBuffers` (the old project, with a github repo at https://github.com/jskeet/protobuf-csharp-port)

**Comment by mikebridge** [comment]
@jskeet Sorry, I should have followed up here.  The version of Akka.NET I was using at the time pulled in a version of protobuf that had this issue, but upgrading to 2.4.1.555 solved the problem.

**Comment by jskeet** [comment]
Okay - that sounds like you're looking at the other project anyway, so I'll close this issue if that's okay.

**Comment by mikebridge** [comment]
Yes, looks like they now use a newer version of the old project.  Thanks!
