### ISSUE TITLE
3.0.0a1 pulled from PyPI?

### ISSUE THREAD

**Issue by vlsd** [google/protobuf#1323]
I was trying to install an older version of `gcloud-python 0.6.0` through `pip` (running an old script) and it errored out due to its dependency on `protobuf 3.0.0a1`. Sure enough, that version seems to have been available from PyPI at the time but has since been removed, making all packages that depend on it fail to build. I don't know if this is the right approach, so please close the issue if I am out of line, but I think the simplest solution to this would be to re-upload the said version to PyPI. Thoughts?

**Comment by xfxyjwf** [comment]
I suppose you mean protobuf 3.0.0-alpha-1? That package is removed because it causes problems for users who depend on versions >= 3.0.0a3. Somehow pip thinks 3.0.0-alpha-1 is newer then 3.0.0a3. See: https://github.com/google/protobuf/issues/855

PyPI doesn't allow us to re-upload the package once removed. Could you use a newer version of gcloud?
