### ISSUE TITLE
SerializeToArray return true when required field not initialized

### ISSUE THREAD

**Issue by liuaifu** [google/protobuf#1341]
```
message User
{
	required string username = 1;
	required string mobile = 2;
}
```
```c++
User user;
user.set_username(pszUserName);
//user.set_mobile(pszMobilePhone);

int nSize = user.ByteSize();
void *pBytes = _malloca(nSize);
auto ptrBytes = std::shared_ptr<void>(pBytes, [](void* p){ _freea(p); });
bool nRet = user.SerializeToArray(pBytes, nSize);
if (!nRet) {
    printf("SerializeToArray fail\n");
}
```
The 'User' have two required fields, i have initialized the first one, but not initialized the second.
In my memory, it should return false, but true now. Is it expected?

my protobuf version is 2.6.1

**Comment by haberman** [comment]
The `IsInitialized()` check only happens when debug mode is enabled ([it's a DCHECK](https://github.com/google/protobuf/blob/master/src/google/protobuf/message_lite.cc#L318)). The assumption is that your app will ensure all required field are set. If you want to check this manually, call `IsInitialized()` yourself prior to serializing.
