### ISSUE TITLE
Filename Options for C++ and ObjC

### ISSUE THREAD

**Issue by gvaish** [google/protobuf#1372]
Right now, [C++](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/cpp/cpp_generator.cc#L117) and [ObjC](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/objectivec/objectivec_generator.cc#L82) compilers have the filenames hardcoded with no flexibility during code generation.

Provide an option to for the filename infix.

Example:

- [ ] `option objc_filename_infix = ".pb"`
    - Will generate `a.pb.h` and `a.pb.m` for `a.proto`.
- [ ] `option cpp_filename_infix = ".pb"`
    - Will generate `a.pb.h` and `a.pb.cc` for `a.proto`.

Thoughts?

**Comment by xfxyjwf** [comment]
This is not easy to implement because we have build tools (probably all build tools that invoke protoc) hardcoding the file name mappings in their code. If protoc suddenly generates a different file, all those build tools will be broken. Since this option also provides very little value (it seems), I'm inclining to say no for this change.

**Comment by gvaish** [comment]
@xfxyjwf It's about providing an option.

The default value can always be the current value so that this change is 100% backward compatible.

It shouldn't break any of the current stuff. I can provide the PR coz I already have it (almost) ready... and yes, it doesn't break any existing thing.

**Comment by xfxyjwf** [comment]
Wouldn't it break if the option is used by a .proto file? I believe the option will causes more problems than the value it can add to protobuf (I actually don't see the value of it).

**Comment by gvaish** [comment]
Here's my take:

* It will not break any tools if this option is not used.
* For those who still want to always use `pbobjc` file extension can override using CLI option (one parameter change in config).
* And, I would argue if [C# generator](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/csharp/csharp_generator.cc#L74) can have the option, why not C++ or ObjC. :-)
    * Question: How would the tools be configured for C# code generation?

Usefulness:

1. For those using [`objc` plugin on 2.x](http://github.com/alexeyxo/protobuf-objc), it will allow drop-in replacement for the generated code and _not require making intrusive changes_ for all `#include` statements. This plugin generates `.pb.{h,m}` files.
    * So, that's a +1 for developers in adoption and faster migration to `protoc v3`.
2. It helps filtering generated code by extension.
    * Not too big an issue 

I'm being selfish here from the adoption and seamless migration standpoint.

If we're looking for a tool to be (preferably) used as de-facto choice, let's make life of its users easy.

Thoughts?

**Comment by gvaish** [comment]
To add to `usefulness` above:

2a. Filter by extension --> Build tools, automation etc.
    * In fact, as people switch from `objc` plugin to `protoc`, the existing build tools may break.

**Comment by xfxyjwf** [comment]
So you are talking about a code generator flag rather than an .proto file option. That's less of concern to me, though I still see no reason to add it for C++. For objective-c, you mentioned it could ease the migration from old objc plugin to the new version. That's a valid point but I'm not sure how much it helps since we are introducing a new objective-c API and that I believe requires some code changes from old objc users. Could you create a separate issue specifically for objective-c?

**Comment by gvaish** [comment]
QQ: How `objc_opt`and `option objc_` different when it comes to the `Generate` method?

As what I could understand:

1. `{lang}_opt` are parsed via `ParseGeneratorParameter` method.
2. The `option {lang}_` are available via `FileDescriptor::options()::{blah}` methods.

Am I correct?

**Comment by gvaish** [comment]
Created #1380.

Feel free to close this.

**Comment by xfxyjwf** [comment]
On Fri, Apr 1, 2016 at 11:07 AM, Gaurav Vaish <notifications@github.com>
wrote:

> QQ: How objc_optand option objc_ different when it comes to the Generate
> method?
>
> As what I could understand:
>
>    1. {lang}_opt are parsed via ParseGeneratorParameter method.
>    2. The option {lang}_ are available via
>    FileDescriptor::options()::{blah} methods.
>
> Am I correct?
>
Yes. Basically code generator flags will only be passed to the specific
code generator, while an option in .proto file will be visible to every
proto consumer as it will be embedded in descriptors.

**Comment by gvaish** [comment]
I have some thoughts running on this.

While discussing with @jskeet on another thread, we concurred that
different options at multiple places is already confusing and overwhelming.

I will try to pen down my thoughts sometime over the next week and seek
your inputs!


- Gaurav

On Friday, April 1, 2016, Feng Xiao <notifications@github.com> wrote:

> On Fri, Apr 1, 2016 at 11:07 AM, Gaurav Vaish <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > QQ: How objc_optand option objc_ different when it comes to the Generate
> > method?
> >
> > As what I could understand:
> >
> > 1. {lang}_opt are parsed via ParseGeneratorParameter method.
> > 2. The option {lang}_ are available via
> > FileDescriptor::options()::{blah} methods.
> >
> > Am I correct?
> >
> Yes. Basically code generator flags will only be passed to the specific
> code generator, while an option in .proto file will be visible to every
> proto consumer as it will be embedded in descriptors.
>
>
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/google/protobuf/issues/1372#issuecomment-204497902>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/google/protobuf/issues/1372#issuecomment-204503949>
>


-- 
- Gaurav
http://bit.ly/1HKpZTg

**Comment by thomasvl** [comment]
[ Commenting here instead of on the objc one to keep things all in one place. ]

I closed the objc one so we can roll up some of the discussions into one place and to hopefully get this sorted out more generally instead of just for ObjC.

One issue with doing this as a generator option is the Well Known Types. If you have a proto that references those, it will still needed to generate the `#include` or `#import` directives using the default names otherwise, those files shipped with the compiler won't be found.

There also could be options if someone puts out a library that uses the non default, and someone tries to integrate that with something else that uses the default.  If there are any overlaps in the proto files, you can get into multiple definition problems based on what gets imported and if >1 gets imported.  This is actually why we went with pbobj.(h,m).  We've seen cases when someone needs a proto for some C++ code they are using and then ends up needing for for some other ObjC code.  So it can become a nightmare of include order battles.

As far as the migration point, seems like there would be enough code changes, the global search and replace for the extension is the least amount of the work, no?

**Comment by thomasvl** [comment]
btw - I'm not opposed to doing this for ObjC, just trying to figure out if it is worth doing in general and/or for just some languages.  The C# one was a surprise to me when you mentioned it (for all the reasons mentioned)

**Comment by gvaish** [comment]
@thomasvl Well, things are different in C# and Java world where the `import` statements are resolved by the compiler and classes looked within a `DLL` or `JAR` file, and there is no concept of `#include` using relative paths pointing to a specific file with `name + extension` that must be resolved.

So, it doesn't really matter in Java / C# / Python / NodeJS etc worlds as much as it does in C++ / ObjC worlds.

Let me give it a deeper thought about this option - whether it's worth having it and if so, what's the optimal solution.
