### ISSUE TITLE
iOS ARC Support

### ISSUE THREAD

**Issue by gvaish** [google/protobuf#1379]
It's more of a question to which I've not been able to find an answer to:
- Why does the `objectivec` compiler not generate ARC code?
  - Are there any limitations enforced by a dependency or otherwise low-level code?

I couldn't find a real need for non-ARC code unless the idea is to support very old versions of ObjC / Xcode.

**Comment by gvaish** [comment]
//cc: @thomasvl (on objc team)

**Comment by thomasvl** [comment]
So ARC inserts a lot of retain/release calls, and can slow some things down.  In our profiling, it did slow down some things like parsing/serialization.  So the support sources wouldn't want to go to ARC for that reason.

The generated sources are mostly just static data, with a bunch of __unsafe_unretained, we might be able to make them compile cleanly as ARC without any real hits, because there isn't real code there, but I'd have to double check to confirm.

**Comment by gvaish** [comment]
@thomasvl Thnx. Let me know when you have an update.

In addition, do you have perf comparision numbers with and without ARC? Would be keen to see how do they compare...

**Comment by thomasvl** [comment]
No real numbers I can publish.  It comes down to picking some proto(s), and running their numbers on some sample data.  Exactly what the the combination of nested messages and field types are can have some larger swings in the numbers.  The more non object types, the less ARC moves the numbers, the more object types, the more they change.

BTW - your question sorta implies you see ARC as only for support old OS versions.  That's not the case, nothing says ObjC code has to be ARC.  ARC can some things simpler for developers because they don't have to do retains/releases/autoreleases them selves, but you still have to pay attention to the memory model because of retain cycles, etc.  Protos is one of those cases, where ARC doesn't really seem to gain much, and since folks like want parsing/serialization to be fast, ARC can be a penalty.

**Comment by thomasvl** [comment]
Took a quick look.  __unsafe_unretained is a good chunk of it, but there are some places with direct memory management calls that would then get changed without ARC.  So it wouldn't currently be transparent to switch over (if someone regenerated and left their project as it, they could have issues since the code would assume ARC, but their compile setup would still have ARC disabled for the sources).

**Comment by gvaish** [comment]
@thomasvl Good points (on NFS for `protoc` and not using ARC).

Let me find some time to run some numbers - again, not for publishing but more for comparision to see the benefits.

When and how, if at all, do we change to ARC can be decided later - based on efforts required. But, if we do decide on ARC, it'd be a breaking change then - what do you think?

Regarding `__unsafe_unretained`. Yes, there are ~100 references in `*_PackagePrivate.h` header files. :-)

**Comment by thomasvl** [comment]
Yea, it could be a breaking change.  The trick will be if we can tweak the generated code into a form where it is "right" with or without ARC, so we don't cause problems for existing projects.

`__unsafe_unretained` usage in all those was needed to allow the consumers of protos to be ARC if they wanted.  That's sorta different problem space, that's something we have to support and have some basic tests to ensure thing can always build/work that way.
