### ISSUE TITLE
Add compiler plugins for Swift

### ISSUE THREAD

**Issue by BenchR267** [google/protobuf#1432]
Swift is very fast evolving language. Added first class support for generating Swift files from proto-declarations would be awesome. I would also love to help with this one, just say where I could start.

**Comment by thomasvl** [comment]
I'm not sure if it makes sense to try to keep an issue open for the whole process of bringing new languages support. I'm find doing that also, since you opened this, I'll let you decide.  :)

I just landed https://github.com/google/protobuf/pull/1442 from @allevato to get an initial design discussion going.

**Comment by BenchR267** [comment]
Ah, that looks very interesting! Good to hear that this is not a completely new idea :) I'll close this one.

**Comment by dpassage** [comment]
BTW, there's an existing third-party plugin for this, works pretty well: https://github.com/alexeyxo/protobuf-swift
