### ISSUE TITLE
C# plugin in beta3 fails to import WellKnown protos

### ISSUE THREAD

**Issue by et1975** [google/protobuf#1568]
When updating from beta2 to beta3 and having installed the protoc from Google.Protobuf.Tools I can't compile my .proto anymore, import fails with:
`google/protobuf/struct.proto: File not found.` and 
`paket-files/prolucid/protoshell/src/main/proto/multilang.proto: Import "google/protobuf/struct.proto" was not found or had errors.`

[.proto](https://github.com/Prolucid/protoshell/blob/master/src/main/proto/multilang.proto)

**Comment by jtattermusch** [comment]
Are you properly setting the proto include path when invoking protoc.exe?

The struct.proto file is present in the Grpc.Protobuf.Tools nuget https://github.com/google/protobuf/blob/cc5296b8692beff00285505dd7062c7d5bcb325a/csharp/Google.Protobuf.Tools.nuspec#L32, but it seems protoc is failing to find it because of you `-I` settings.

**Comment by jtattermusch** [comment]
Please note that the relative path to the google/protobuf directory with respect to protoc.exe has changed in beta3 (because we added precompiled versions of protoc for other platforms as well).

**Comment by et1975** [comment]
Thanks, explicitly adding an `-I` to the tools folder solved the import problem.
