### ISSUE TITLE
latest descriptor.proto does not compile with protoc 2.6.1

### ISSUE THREAD

**Issue by thesamet** [google/protobuf#1669]
This issue impact users who obtain proto sources from protobuf-java 3.0.0-beta-3, but still from some reason use protoc 2.6.1 to compile them.

The latest version of `src/google/protobuf/descriptor.proto` does not compile with protoc v2.6.1. This breakage was introduced between 3.0.0-beta-2 and 3.0.0-beta-3.

```
src/google/protobuf/descriptor.proto:386:3: Expected "required", "optional", or "repeated".
src/google/protobuf/descriptor.proto:386:12: Expected field name.
```

The culprint is a line that has the reserved field keyword: ```reserved 38;```

**Comment by xfxyjwf** [comment]
Can you explain a bit more about the reason to use protoc 2.6.1 with protobuf-java-3.0.0-beta-3? We want to make it easy for users to access the latest protoc. Currently we include pre-built protoc binaries for linux, mac and windows in our release page. If you have difficulties to get the binary, please let us know how we can help.

**Comment by stepancheg** [comment]
I have the same issue.

I'm the author of the [rust-protobuf](https://github.com/stepancheg/rust-protobuf) library. Library should be buildable with protobuf 2.6.1, because some people still use protobuf 2.6.1. My default protoc version is 2.6.1.

However, even if I use protoc 2.6.1, I need to use `descriptor.proto` from protobuf 3.0.0 to properly generate code for `syntax = "proto3"`, e. g. to generate map fields or to use `client_streaming` and `server_streaming` options in service definitions.

So I need to bundle `descriptor.proto` from protobuf 3.0.0 and still be able to compile it with protoc 2.6.1.

Obviously I can comment out `reserved 38` line, but it would be better if rust-protobuf used unmodified `descriptor.proto`.
