### ISSUE TITLE
JSON Serialization with Objective-C

### ISSUE THREAD

**Issue by woigl** [google/protobuf#1675]
Is the JSON serialization in Objective-C available?

**Comment by thomasvl** [comment]
Not currently. To support it we'd likely need to include a lot more string data so it would bloat the binaries.  Since the primary use of Objective C is for mobile, the binary encoding tend to be a better choice (both wire size and code size).

Is there a specific reason you are after JSON serialization?

**Comment by woigl** [comment]
Well, you've got a valid point. **Do you see a possibility to implement this optional?** Like through some compiler defines or staff like that.

I am using it for Rest-Calls and not each Rest-Service uses protobuf, but with the JSON serialization we could use on one side protobuf and on the other side only JSON.

**Comment by thomasvl** [comment]
I don't think compiler defines would work for the folks using CocoaPods as I don't think they could easily inject it into the dependency, and if we made it a different subspec with the default, someone could end up with a dep on the version with and the version without out, leading to trouble.

Since ObjC doesn't really deadstrip, trying to make it optional also gets complex.  It tends to have to be exposed as C symbols instead.

I'm guessing this is some other company's service?

**Comment by woigl** [comment]
Well, it would have been a nice feature. Anyway, I think that I can write it myself as I basically just need to match the JSON against my proto's.

Thanks anyway

**Comment by larrytin** [comment]
@woigl Have you implemented this feature yet?

**Comment by thomasvl** [comment]
Closing this since there currently aren't any plans to add it, but will use this issue as the "main" one if folks ask about it again.
