### ISSUE TITLE
"reserved" keyword isn't recognized by 2.6.1 protoc compiler

### ISSUE THREAD

**Issue by ben51** [google/protobuf#1747]
The CHANGES.txt and the https://developers.google.com/protocol-buffers/docs/proto#reserved page explain how to use the "reserved" keyword to forbid using a set of fields. Unfortunately it seems that the latest proto2 compiler (ie. 2.6.1) doesn't recognize it.
My test was to take the Foo message given in the doc and here is what I got running the protoc command:
src/main/protobuf/metadata_proto.proto:97:3: Expected "required", "optional", or "repeated".
src/main/protobuf/metadata_proto.proto:97:12: Expected field name.

Is it expected not to support such a keyword in proto2 ? If so could you update the documentation ?

Thanks

**Comment by xfxyjwf** [comment]
The keyword is supported in proto2 syntax, but you need to use protobuf-3.0.0-beta-3 to use it. Note that protobuf-3.0.0 doesn't correspond to proto3. Protobuf-3.0.0 supports both proto2 and proto3 syntax and some proto2 features (like reserved, map fields) are only supported in protobuf-3.0.0.

**Comment by ben51** [comment]
Thank you, I wasn't aware of this release process :)

**Comment by zoller27osu** [comment]
The above should state that you need protobuf-**compiler** (protoc) version 3+ to use those features. They were backported to proto2 syntax precisely because they are things only the protobuf compiler needs to be concerned with ("reserved" being a protobuf compile-time check and "map" being shorthand for previously existing syntax).
