### ISSUE TITLE
How to get custom field option? [objc]

### ISSUE THREAD

**Issue by dnkoutso** [google/protobuf#1779]
Is it possible to access all custom options for a field with the current API? We have a few custom field options that we want to access at runtime.

**Comment by dnkoutso** [comment]
Seems like an equivalent `toProto()` from java does not exist for ObjC is this true? Given a `GPBFieldDescriptor` to output a `GPBFieldDescriptorProto`.

**Comment by thomasvl** [comment]
Yea, so the GPB*Descriptor classes aren't the same as they are for some of the languages where the full descriptor is captured.  Most of the mobile spaces, you don't want the full descriptor because it is just binary bloat.  So the ObjC GPB*Descriptor classes really only exist to feed the minimal information the runtime needs to function.  So it intentionally doesn't try to carry all that data (including options) along.

**Comment by thomasvl** [comment]
Making it a generation option also becomes a problem as someone ends up with two dependencies that share a comment proto dependency, but one wants an option and the other doesn't.  I've seen that happen before with C++ between "lite" and "full" runtimes there.

**Comment by dnkoutso** [comment]
@thomasvl thank you for the response. This confirms my suspicion.

We already have a tiny fork so we will be able to manage it on our side for our objc needs.
