### ISSUE TITLE
JavaScript Circular Deps

### ISSUE THREAD

**Issue by xR3b0rn** [google/protobuf#1784]
Using the protoc-3.0.0-beta-3 or protoc-3.0.0-beta-2 in conjunction with a protobuf file in which a messages A uses message B which uses message A, leads in JavaScript to circular dependencies. I.e. messagea.js requires messageb.js and messageb.js requries messagea.js.

Example protobuf-file:
`message A
{
    required B b = 1;
}
message B
{
    require A a = 1;
}`

protoc Procuces 2 JavaScript-files: a.js and b.js.
a.js requries b.js and b.js requires a.js.
This leads to errors.

**Comment by haberman** [comment]
It sounds like you are using `import_style=closure` (the default) without `library=`. It is true that this mode of operation can't handle circular dependencies like this.

You have two options for fixing the problem:

1. use `import_style=commonjs` to have CommonJS imports instead.
2. use `library=myprotos_lib.js` so that all of the protoc output is placed into a single output file.

For more info see the readme: https://github.com/google/protobuf/tree/master/js
