### ISSUE TITLE
Add Swift options to descriptor.proto

### ISSUE THREAD

**Issue by kientzle** [google/protobuf#1833]
I would like to see the following two options added to descriptor.proto to support Swift code generation:
# File-level option: `swift_prefix`

```
option swift_prefix = "string";
```

When set, all generated top-level Swift types would be prefixed with this string.  If not set, a default prefix is generated from the package name.  If neither this nor a package name is provided, then the generated types are not prefixed.

The behavior here is slightly different than that in the recent Swift design proposal:  That document suggests that swift_prefix should cause type aliases to be emitted.  However, one common use of this is to avoid name clashes which cannot be fixed with a type alias.

I suggest this be added with ID 39.
# Message-level option: `swift_additional_protocols`
## This suggestion is withdrawn; it is not needed.

```
option swift_additional_protocols = "string";
```

Generated Swift code can be customized in many ways by Swift extensions without requiring special code generation options.  The only exception (in Swift 3) is that a Swift extension cannot add protocol conformances.  The text of this option is added to the protocol conformances for the generated message type with a preceding comma (`,`) added if necessary to separate it from other generated conformances.  For example, google.protobuf.Duration might include

```
option swift_additional_protocols = "FloatLiteralConvertible";
```

Note that the implementation of such a conformance can be added in a Swift extension, so there is no need for the code generator to have any special knowledge of these conformances.

I suggest this be added with ID 8.

**Comment by xfxyjwf** [comment]
@pherl @thomasvl

**Comment by sergiocampama** [comment]
@dmaclach

**Comment by allevato** [comment]
Tim,

Based on the discussion in <https://github.com/google/protobuf/pull/1442#discussion_r72005149>, how would you feel about a `swift_package_prefix` option that replaces the `Package_Subpackage_` part of `Package_Subpackage_Message` with a different prefix (similar to the way Objective-C works today)? It's not ideal, but it seems like the best option until Swift has some kind of proper namespacing support, and this would not require users to manually curate a potentially long list of their own typealiases.

For the second point, you say "The only exception (in Swift 3) is that a Swift extension cannot add protocol conformances". I don't believe that's the case, since that's one of the major features of extensions in Swift (I've personally used it a number of times). The following seems to work in both Swift 2 and Swift 3, from my own testing:

```swift
struct SomeValue {
  var value: Double
}

extension SomeValue: FloatLiteralConvertible {
  init(floatLiteral value: Double) {
    self.init(value: value)
  }
}

let x: SomeValue = 5.0
x.value  // 5.0
```

Given that, the second option you're proposing shouldn't be necessary; extensions for well-known types can be added whether or not they add protocol conformances.

**Comment by allevato** [comment]
On a side note, however, I would argue that providing an implicit creation of a `Duration` from a `Float` literal feels unSwifty; aside from Swift's eschewing of most implicit conversions in general, it seems important to the reader that a `Duration` is a structured protobuf message with its own fields and methods and seeing `let x: Duration = 5.0` in code, or worse, passing 5.0 to a method that takes a `Duration` as a parameter, has the potential to add confusion.

**Comment by kientzle** [comment]
> how would you feel about a swift_package_prefix option that replaces the Package_Subpackage_ part of Package_Subpackage_Message with a different prefix (similar to the way Objective-C works today)?

That's exactly the behavior I'm proposing for swift_prefix.

To be specific, in the normal case, I expect that:
```
package foo.bar;
message Baz { }
```
becomes
```
struct Foo_Bar_Baz { ... }
```

I am proposing that:
```
package foo.bar;
option swift_prefix="My";
message Baz { }
```
generate
```
struct MyBaz { ... }
```

**Comment by kientzle** [comment]
> ... the second option you're proposing shouldn't be necessary; extensions for well-known types can be added whether or not they add protocol conformances.

You seem to be right about this.  I withdraw the second option suggested.

**Comment by thomasvl** [comment]
Cycling back to this - Looks like we're down to just the file level option for a prefix.  There is a question about if it should generate a type alias or should change the generated type names.

Changing the types names generated:
- One of the arguments seemed to be to work around cases where two proto files use the same package/type naming (and would other wise conflict).  Personally, I'm not sure how valid that is, as those protos files won't work in most other languages because of the conflict (protoc won't even allow you to generate them together because of this).  It also seems to be purely from trying to use some of the unittesting protos in a single binary when they were authored to be unique to each of the test binaries they are used in instead of shared across binaries.
- This would shrink binaries some since the symbol names likely will be shorter due the the prefixes.

Just generating prefixes:
- Editors may or may not pick up the alias to complete.

Any other advantages/disadvantages to these?

**Comment by allevato** [comment]
If we just generate convenience typealiases but leave all the other references to the types the same, that could be a source of confusion because autocomplete would still show the full names everywhere. For example,

```swift
struct Foo_Bar_Baz {
  var quux: Foo_Bar_Quux
}
struct Foo_Bar_Quux { ... }

typealias FBBaz = Foo_Bar_Baz
typealias FBQuux = Foo_Bar_Quux
```

Someone typing `myBaz.quux = ...` is going to see `Foo_Bar_Quux` but think "Hmm, I was expecting to see `FBQuux`, why is this different?" If we solved that by using the typealiases *there* as well, then there's really no reason to not just have that *be* the name in the first place.

Since they would only exist to save a little typing at the point of usage, it's hard to rationalize adding them. Let's just say that the prefix replaces the package portion of the name and drop what we were thinking about typealiases.
