### ISSUE TITLE
C#: Enum serialization/deserialization issue

### ISSUE THREAD

**Issue by sharadKhan** [google/protobuf#1948]
Enum values are serialized as string rather than numeric value. Is there a way to support numeric value.

**Comment by xfxyjwf** [comment]
You mean the serialized enum values in JSON format?

**Comment by sharadKhan** [comment]
Yes, serialized value is string rather than value.

**Comment by jskeet** [comment]
Yes, this is deliberate - whenever the enum value is a defined (named) one, it will be serialized as a string. If the value isn't one known to the generated code, the numeric value will be used instead.

There's no way of forcing all enum values to be serialized as numbers instead of strings. It would be possible, but it's not implemented at the moment. Have you seen this implemented elsewhere?

**Comment by sharadKhan** [comment]
Thank you Jon.
Newtonsoft serializes all enum values as numbers by default.

**Comment by jskeet** [comment]
Sorry for not being clearer - I mean within protobuf JSON implementations, have you seen this feature?

Definitely worth leaving open as a feature request, but I think it would ideally be implemented as an option across JSON serializers in all languages rather than just C#.

**Comment by xfxyjwf** [comment]
I don't think any of our existing JSON implementations have this option, though there is another internal request about adding it for Java, so it's likely an useful feature for some users. I plan to add it for Java after I fix existing conformance issues.
