### ISSUE TITLE
Parsing GPBMessages with an extensionRegistry by default in ObjC

### ISSUE THREAD

**Issue by justinseanmartin** [google/protobuf#1954]
We're converting from using generated C++ protos to the native ObjC output. In the process of conversion, we got bit by not passing a extensionRegistry on deserialization from data. When we went to access the property using `-[GPBMessage getExtension:]` we are returned the default value and `-[GPBMessage hasExtension:]` returns NO.

Doesn't the protoc compiler create a default extensionRegistry for every generated file by default? Couldn't it use that to parse by default if none is specified? Is there a downside to doing this? 

CC: @thomasvl

**Comment by thomasvl** [comment]
The registry in exposed off the message classes are just the ones defined on that message.  The registry exposed off the Root for a given file are all extensions defined in the file (file level and messages within the file).  So it will only get those extension parsed.  Extensions could be declared in other files for that message class, so you need to use a registry from that other file or make one merging the files you need.  So while that might work for some it isn't complete.

I believe C++ avoids some of this because it has a bunch of static initializer that have to run at startup to make master registry.  While useful, it works best for servers, for clients, it means your app startup is delayed while everything is constructed.

**Comment by justinseanmartin** [comment]
The registry exposed off the Root contains extensions for the given file and any imported protos. But your point is still valid that it might still be incomplete.

This is a potential hazard in the ObjC proto compiler that doesn't exist in the C++ version. I think there would be a general solution that'd work and still not require an excessive amount of work at startup. I don't know enough of codebase to say what it is, but I can do some exploration.

Do you see this as being an issue? If so, any thoughts on what an acceptable solution might look like to you? Thanks in advance.

**Comment by thomasvl** [comment]
I believe Java also requires passing an extension registry.  Swift will also.  So it is just something that will be different with some languages.

**Comment by thomasvl** [comment]
Sorry, meant to add, my one concern with trying to provide a default that is only partial, is that it could end up more confusing to folks as instead of no extensions being handled without a registry, some are.

**Comment by justinseanmartin** [comment]
My thought was to not pass a default that is only partial, but rather to pass a full registry. Do you not think that is feasible? Or not worth the tradeoffs?

**Comment by thomasvl** [comment]
To do it it means a hit at startup or the first parse to build that registry.  So I don't think it would be acceptable.

**Comment by justinseanmartin** [comment]
Ok, I'll close this issue then for tracking. We may implement something like this in our own codebase as I believe the risk of not doing this correctly is worse than the hit to startup time for enumerating the extensions. Thanks for the input!
