### ISSUE TITLE
the return value of getter should sometimes be void!!

### ISSUE THREAD

**Issue by wangkaibule** [google/protobuf#202]
It is indeed a good idea to make the return value of  a message getter functions to be a builder's reference.But it turns out that these getters cannot be treated as normal getters at all...(what a pity..)
Seriously, these getters cannot be recognized by some already implemented APIs which think getters should have void return.
So ,I demand an option to switch the return value of getters' return value.

**Comment by xfxyjwf** [comment]
Since you mentioned builder, I guess you are talking about Java. Sounds like you are using some other reflection based library to manipulate protobuf messages/builders? We don't plan to support that. If you want to manipulate reflectively, you can use protobuf's own reflection API (methods like Message.getField(...) etc.).
