### ISSUE TITLE
Export functions to convert between C/Python protos to Python extensions.

### ISSUE THREAD

**Issue by ioctl0** [google/protobuf#2093]
Currently, a python extension that wishes to return protos to python code must serialize them, and de-serialize using python methods. It would be convenient to expose the underlying Message objects to C-language extensions.

There appears to be a start to this functionality in pyext/python_protobuf.h, but the corresponding .cc file was deleted at some point (by mistake?), and it was never exported in a capsule.

**Comment by anandolee** [comment]
It was deleted by mistake. Will add this back

**Comment by anandolee** [comment]
Added in internal. python_protobuf.cc should be there in next release.

**Comment by xfxyjwf** [comment]
It smells bad to me to expose this in public API. How the Python protos are implemented is an implementation detail. It's especially so regarding to how the internal C++ objects are managed. Exposing these C++ objects for public use will make it significantly harder to change/optimize the python C++ implementation later and the exposed API itself will also be very hard to use correctly because of the very complicated ownership management in Python C++ wrapper.
