### ISSUE TITLE
c# suppress sealed class

### ISSUE THREAD

**Issue by jgrandyxignite** [google/protobuf#2154]
@jskeet is there `protoc `option or `proto3` notation to suppress sealed class attribute ? 

currently C# `protoc` will gen :

`public sealed partial class TestMessage : pb::IMessage<TickMessage> {`

however this eliminates ability to create additional partial classes with additional decorators , inheritance ,  interface implementations

for example , if `protoc' had option to create : 

`TestMessage.cs`
`public partial class TestMessage : pb::IMessage<TickMessage> {`

then a custom generator could create : 
` TestMessage_Partial.cs`
`public partial class TestMessage : CacheableObject {`

**Comment by jskeet** [comment]
You can already write

```csharp
public partial class TestMessage : CacheableObject
```

It being sealed doesn't stop you from specifying a base class.

**Comment by jgrandyxignite** [comment]
@jskeet ah yes right you are - but what if you're attempting to translate a set of types with hierarchical inheritance ( as expressed in xml , for example ) to proto3 + generated-classes ?  

Are there reasons why protoc generates C# class as sealed ?  ( or I suppose Java class as final )

**Comment by jskeet** [comment]
> but what if you're attempting to translate a set of types with hierarchical inheritance ( as expressed in xml , for example ) to proto3 + generated-classes ?

Then you need to think of an alternative approach, because proto simply doesn't "do" inheritance, only composition. I would strongly urge you to just go with that instead of fighting it - you'll end up with a much simpler experience.

> Are there reasons why protoc generates C# class as sealed ? ( or I suppose Java class as final )

In Java it's vital as proto messages are immutable. In C#, messages are mutable, so we *could* unseal the classes - but there are all kinds of extra difficulties introduced by that. How do you parse to a derived type, for example? It's all much simpler without inheritance, and as protos don't model inheritance anyway, I felt it best to enforce that in the .NET type system too.

**Comment by StingyJack** [comment]
> we could unseal the classes - but there are all kinds of extra difficulties introduced by that. How do you parse to a derived type, for example?

@jskeet - You all really should unseal them in this situation and probably for any future codegen tools. I think that the problems with derived types would not be the problems of the generation tool author to solve. This is primarily because the the generated code does not belong to the tool author in the first place. A code generation tool using protections like this is just like forcing DRM on users.

**Comment by MattyBoy4444** [comment]
At least they could make it optional on generation.

**Comment by xp10102232** [comment]
您的来信我已收到，我会尽快处理，如您急需，请电话告知……
