### ISSUE TITLE
Support HTML Unescaping in Java JsonFormat

### ISSUE THREAD

**Issue by mingfai** [google/protobuf#2342]
(edited, removed incorrect info about Gson.disableHtmlEscaping())
(edited again, the original "\346\270\254\350\251\246" was incorrect)
JsonFormat parser isn't able to parse string content with escaped unicode string, e.g. ``` "\u6e2c\u8a66" ("測試")```. After parsed, the string field contains the unescaped unicode string rather than the intended unicode string.

in JavaFormat.java, it explicitly build a Gson instance with disableHtmlEscaping(). It affects printing json string, and not relevant to parsing json string/reader.  ```new GsonBuilder().disableHtmlEscaping()```

**Comment by xfxyjwf** [comment]
Is "\346\270\254\350\251\246" even a valid JSON string according to the JSON spec? http://www.json.org/

disableHtmlEscaping() was added explicitly because the html escape behavior is undesirable. Given that JSON spec has nothing to do with html escaping, I do not think the JsonFormat class should provide an option for that. If you want to parse "\346\270\254\350\251\246" as "測試", I suggest you do a separate html escaping pass before feeding the String to JsonFormat.

**Comment by mingfai** [comment]
sorry i provided incorrect info again. 
the source unicode string is "\u6e2c\u8a66" not "\346\270\254\350\251\246". 

when I parse the json Gson directly, it is able to turn the value as "測試". but when I use JsonFormat to parse the value, it is turned to "\346\270\254\350\251\246". Under the hook JsonFormat uses the same Gson library. I wonder why the behaviour is different.

**Comment by mingfai** [comment]
this issue is a false alert. the toString() behaviour caused a little bit confusion. apologize about it.
