### ISSUE TITLE
C# add option to generate code with custom Suffix/Prefix

### ISSUE THREAD

**Issue by sergiorykov** [google/protobuf#2352]
It will be useful (at least for me :) ) to be able to customize class name generation:
```
syntax = "proto3";
option csharp_namespace = "Google.Protobuf.WellKnownTypes";
option csharp_classname_suffix = "Proto";
option csharp_classname_prefix = "Super";
message Timestamp { ... }
``` 

```
namespace Google.Protobuf.WellKnownTypes
{
  public sealed partial class SuperTimestampProto : IMessage<SuperTimestampProto> { ... }
}
```

Actually I need this kind of customization to **disable intersections with domain type names**, especially, when  proto messages have _good_ names. I only need suffix, but propose to add both options as they are complementary.

**Comment by xfxyjwf** [comment]
We generally discourage the addition of any new proto options. In your case, is the csharp_namespace  option not enough to avoid conflicts?

**Comment by sergiorykov** [comment]
When I map DTO generated from .proto they have the same names and differs only by namespaces. It confuses a lot.

Actually, ObjectiveC has this kind of option (as namespace alternative)

```
option objc_class_prefix="ASDFProtos";
```

**Comment by xfxyjwf** [comment]
ObjectiveC doesn't support namespace, so objc_class_prefix serves the same purpose as csharp_namespace. I don't think it's a good idea to introduce another option in C#.

In your case, why not just change the name in the .proto file to avoid the confusion? In protobuf we have a Descriptor class and name the corresponding proto type as DescriptorProto. You can use the same convention.

**Comment by sergiorykov** [comment]
Yes, objc uses it as namespace alternative. 

Do you suggest to write .proto files with all this mess?
```
message SomeCommandProto {
      SomeCommandConfigProto config = 1;
      OtherOptionsProto other_options = 2;
      OneMoreOptionsProto one_more = 3;
}

message SomeCommandConfigProto {
}

message OtherOptionsProto {
}

message OneMoreOptionsProto {
}
```

We use the same .proto files on several platforms: Win/Unix/Android/iOS/STM(nanopb) 
To solve this cosmetic issue for C# when you work with two types with equal names (because they have good names for domain too) but in different namespaces Do I have to write ugly protos for other team members?

**Comment by xfxyjwf** [comment]
It's your team's decision about what's the most appropriate name to use for these proto types. The XXXProto convention is what we use in protobuf. If you think it's ugly, you can use other naming conventions as you like.

**Comment by sergiorykov** [comment]
Can you please show examples? [Style Guide](https://developers.google.com/protocol-buffers/docs/style#message-and-field-names) doesn't tell anything about it. 

Inside of .proto definitions I want to have message contracts as clear and readable as possible. Customizing codegeneration from .proto files is almost the same as customizing AutoMapper: I need to convert data from binary format to another.

**Comment by sergiorykov** [comment]
I'm sorry, if my english not so polite as I want. That's my second language. 

I think it's not a question - It's a feature proposal and It's really valuable for .Net developers.

**Comment by jskeet** [comment]
I'm with @xfxyjwf here - I would rather not let the options proliferate.

**Comment by xfxyjwf** [comment]
I'm marking this as a feature request, but I do not think it's a worthy addition to protobuf library. Due to the quadratic complexity options can add to protobuf library, we should only add one when it's necessary to solve a common problem. In this case, it seems a very specific style preference that I hardly think is universal.

**Comment by sergiorykov** [comment]
Ok. @jskeet thanks for response!

**Comment by anandolee** [comment]
Close this isuue as everyone agree on not add the option

**Comment by scooter-dangle** [comment]
I was looking for this as a language-agnostic option rather than specifically for C#. It came up when a team defining upstream data didn't account for a keyword in one of the downstream consumer's programming languages (Java, in this case). If Java had a verbatim identifier syntax similar to C#'s `@` sigil, we'd be fine. Unfortunately, we'll have to try to change the upstream definition and all the already generated and working clients in non-Java languages.

We can guard against this in the future by checking against all the keywords in Java in CI for the upstream declarations, but that isn't a forward-compatible approach with respect to programming languages we don't currently use but _might_ in the future. (Including, possibly, programming languages that haven't yet been created for which the set of keywords/reserved words is unknowable.)
