### ISSUE TITLE
Test failure on OpenBSD

### ISSUE THREAD

**Issue by vext01** [google/protobuf#2419]
On OpenBSD-current/amd64 on protobuf 3.1.0 built with gcc-4.9.3:

```
...
[----------] 1 test from Anytest
[ RUN      ] Anytest.TreatAsSet
[       OK ] Anytest.TreatAsSet (0 ms)
[----------] 1 test from Anytest (0 ms total)

[----------] 7 tests from JsonUtilTest
[ RUN      ] JsonUtilTest.TestWhitespaces
[       OK ] JsonUtilTest.TestWhitespaces (1 ms)
[ RUN      ] JsonUtilTest.TestDefaultValues
/usr/local/pobj/protobuf-cpp-3.1.0/protobuf-3.1.0/src/google/protobuf/util/json_util_test.cc:158: Failure
Value of: ToJson(m, options)
  Actual: "{\"boolValue\":false,\"int32Value\":0,\"int64Value\":\"0\",\"uint32Value\":0,\"uint64Value\":\"0\",\"floatValue\":0,\"doubleValue\":0,\"stringValue\":\"i am a test string value\",\"bytesValue\":\"bWEgIGEgc2V0YiB0ZXR5diBzdWxhZXU=\",\"enumValue\":\"FOO\",\"repeatedBoolValue\":[],\"repeatedInt32Value\":[],\"repeatedInt64Value\":[],\"repeatedUint32Value\":[],\"repeatedUint64Value\":[],\"repeatedFloatValue\":[],\"repeatedDoubleValue\":[],\"repeatedStringValue\":[],\"repeatedBytesValue\":[],\"repeatedEnumValue\":[],\"repeatedMessageValue\":[]}"
Expected: "{\"boolValue\":false," "\"int32Value\":0," "\"int64Value\":\"0\"," "\"uint32Value\":0," "\"uint64Value\":\"0\"," "\"floatValue\":0," "\"doubleValue\":0," "\"stringValue\":\"i am a test string value\"," "\"bytesValue\":\"aSBhbSBhIHRlc3QgYnl0ZXMgdmFsdWU=\"," "\"enumValue\":\"FOO\"," "\"repeatedBoolValue\":[]," "\"repeatedInt32Value\":[]," "\"repeatedInt64Value\":[]," "\"repeatedUint32Value\":[]," "\"repeatedUint64Value\":[]," "\"repeatedFloatValue\":[]," "\"repeatedDoubleValue\":[]," "\"repeatedStringValue\":[]," "\"repeatedBytesValue\":[]," "\"repeatedEnumValue\":[]," "\"repeatedMessageValue\":[]" "}"
Which is: "{\"boolValue\":false,\"int32Value\":0,\"int64Value\":\"0\",\"uint32Value\":0,\"uint64Value\":\"0\",\"floatValue\":0,\"doubleValue\":0,\"stringValue\":\"i am a test string value\",\"bytesValue\":\"aSBhbSBhIHRlc3QgYnl0ZXMgdmFsdWU=\",\"enumValue\":\"FOO\",\"repeatedBoolValue\":[],\"repeatedInt32Value\":[],\"repeatedInt64Value\":[],\"repeatedUint32Value\":[],\"repeatedUint64Value\":[],\"repeatedFloatValue\":[],\"repeatedDoubleValue\":[],\"repeatedStringValue\":[],\"repeatedBytesValue\":[],\"repeatedEnumValue\":[],\"repeatedMessageValue\":[]}"
[  FAILED  ] JsonUtilTest.TestDefaultValues (1 ms)
```

Some kind of problem with quotes?

**Comment by vext01** [comment]
Looking at this again, it looks to me like the expected outcome is wrong...

**Comment by xfxyjwf** [comment]
It seems the only difference is in the bytes field. I suppose it's a platform dependent bug. It's unlikely for the expected outcome to be wrong though, because the same tests pass on our Travis/Appveyor/Jenkins setups.

**Comment by vext01** [comment]
Ah, look again. The outcomes are the same, just one has had the adjacent double quoted C++ strings concatenated.

That's weird...

Is there a specific version of g++ or gtest that is needed here? Some compiler/test flag maybe?

**Comment by acozzette** [comment]
@vext01 I think if you look carefully the bytes fields actually are different. You're right that there is a small formatting difference between the "Expected:" and "Which is:" lines, but that is just because the former shows the literal text from the source file while the latter represents the string evaluated from that. The "Actual:" line is substantially different from the other two.

The actual value for the bytes_value field was `GEgc2V0YiB0ZXR5diBzdWxhZXU=` while the expected value for that is `aSBhbSBhIHRlc3QgYnl0ZXMgdmFsdWU`. These are both supposed to be the base64 encoding of the string `i am a test bytes value`. But if you base64-decode the actual output you get `ma  a setb tetyv sulaeu`. This is almost an anagram of the original text, so it seems as if the base64 encoding step is somehow getting jumbled up in your environment.

**Comment by ramrunner** [comment]
@vext01 @acozzette so ultimately the RenderBytes in /src/google/protobuf/util/internal/json_objectwriter.cc which calls WebSafeBase64EscapeWithPadding or Base64Escape
which both ultimately invoke Base64EscapeInternal from src/google/protobuf/stubs/strutil.cc 
but i haven't been able yet to find out why it behaves as mentioned.

**Comment by xfxyjwf** [comment]
@ramrunner This very much looks like an endian issue. Base64EscapeInternal calls:
```cpp
uint32 in = BigEndian::Load32(cur_src) >> 8;
```
Can you check if BigEndian::IsLittleEndian() gives the correct value for your environment?
https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/src/google/protobuf/stubs/port.h#L401

**Comment by ramrunner** [comment]
@xfxyjwf  so indeed it's endianess and i managed to fix it. from what i see noone cares setting PROTOBUF_LITTLE_ENDIAN . and i'm wondering why on other little endian platforms it works.
does the following configure.ac patch look reasonable to you?
```
diff --git a/configure.ac b/configure.ac
index 896f347..c3ae08b 100644
--- a/configure.ac
+++ b/configure.ac
@@ -101,6 +101,15 @@ AC_FUNC_MEMCMP
 AC_FUNC_STRTOD
 AC_CHECK_FUNCS([ftruncate memset mkdir strchr strerror strtol])

+#endianess
+AC_CHECK_HEADERS([endian.h],
+ AC_TRY_COMPILE([#include ], [switch (1) { case __LITTLE_ENDIAN: break; case __BYTE_ORDER: break; } ],[is_little_endian=0], [is_little_endian=1]),
+ AC_MSG_RESULT([Can't Determine Endianess])
+)
+if test $is_little_endian = 1 ; then
+  CXXFLAGS="$CXXFLAGS -DPROTOBUF_LITTLE_ENDIAN"
+fi
+
 # Check for zlib.
 HAVE_ZLIB=0
 AS_IF([test "$with_zlib" != no], [
```

**Comment by ramrunner** [comment]
actually sorry but this as is won't work cause in the beginning of the file there is an
```
#undef PROTOBUF_LITTLE_ENDIAN
```
what do you think is the correct way to proceed here? should we create another name (like HOST_LITTLE_ENDIAN ?) that is passed from the configure? 
it seems that some comments are hinting towards something like that cause PROTOBUF_LITTLE_ENDIAN is also used in coded_stream.

**Comment by xfxyjwf** [comment]
@ramrunner Thanks for helping. I would prefer a fix that applies to the source code instead of the build configure though. That's because we build protobuf code with different build tools (such as cmake/bazel) and updating configure.ac does not fix the problem with other build tools.

In the code we are detecting the endian with this:
https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/src/google/protobuf/stubs/port.h#L63

Probably we are missing some macros for OpenBSD?

**Comment by ramrunner** [comment]
@xfxyjwf ok finally got it. 
BSD sys/param.h does not deal with endianess. cause it actually shouldn't
there is endian.h for that. and actually endian.h is considered POSIX since 2011
http://www.opengroup.org/austin/docs/austin_514.txt
so if on that line we also include endian.h the BYTE_ORDER macro will be defined and it will equal to the appropriate machine {LITTLE,BIG}_ENDIAN
anyway i am sending a PR in a bit that will include endian.h if __OpenBSD__ defined. i understand that the android SDK might not have it although it would be nice to. :)

**Comment by vext01** [comment]
Thanks @ramrunner!

**Comment by xfxyjwf** [comment]
Closing as the fix https://github.com/google/protobuf/pull/2445 is in.
