### ISSUE TITLE
Inconsistency when parsing -0/"-0" in JSON in C++

### ISSUE THREAD

**Issue by allevato** [google/protobuf#2474]
I've noticed the following inconsistency in the way `-0` and `"-0"` are treated when parsing JSON in C++.

Imagine the following proto:

```protobuf
syntax = "proto3";

message Test {
	uint64 ufield = 1;
	sint64 sfield = 2;
}
```

Parsing the following JSON strings yields the following results:

* `{"sfield": -0}` -> success, `sfield == 0`
* `{"sfield": "-0"}` -> success, `sfield == 0`
* `{"ufield": -0}` -> success, `ufield == 0`
* `{"ufield": "-0"}` -> fails, `ufield: invalid value "-0" for type TYPE_UINT64`

I believe the inconsistency is because `-0` (unquoted) is converted to a number during scanning based on the presence of the minus sign, which calls `safe_strto64` and succeeds; whereas `"-0"` (quoted) is converted within `DataPiece` after the it's known that the field type is `uint64`, so it calls `safe_strtou64` instead, which fails if it starts with a minus sign.

Should this behavior be fixed (which might complicate the handling of quoted numbers to some degree), or should `-0`/`"-0"` just be treated as undefined behavior (since they're really only a characteristic of IEEE 754 and don't apply to integers)?

**Comment by xfxyjwf** [comment]
-0 should be accepted because it's a valid JSON numeric value and is equivalent to 0. For the "-0" case, the current C++ behavior kind of makes sense to me. When parsing integers, the parser is more lenient on numeric values. For example, 1.234e3 will be accepted as equal to 1234. That's because they are equivalent JSON values (e.g., you can't distinguish between the two in Javascript). However, when the value is a double-quoted string, whether it's equivalent or whether it's valid at all is entirely up to protobuf JSON parser to interpret. And in that case being strict on what it accepts depending on the field type doesn't seem a bad idea. In this sense the current behavior looks reasonable to me.
