### ISSUE TITLE
why messge type  remove 'required,optional'?

### ISSUE THREAD

**Issue by bullyork** [google/protobuf#2497]
The 'required,optional' types are useful for client to know which param is required and which is optional.

**Comment by seishun** [comment]
You mean in proto3? Because proto3 doesn't have a notion of presence anymore, so optional and required doesn't make sense.

**Comment by xfxyjwf** [comment]
We dropped required fields in proto3 because required fields are generally considered harmful and violating protobuf's compatibility semantics. The whole idea of using protobuf is that it allows you to add/remove fields from your protocol definition while still being fully forward/backward compatible with newer/older binaries. Required fields break this though. You can never safely add a required field to a .proto definition, nor can you safely remove an existing required field because both of these actions break wire compatibility. For example, if you add a required field to a .proto definition, binaries built with the new definition won't be able to parse data serialized using the old definition because the required field is not present in old data. In a complex system where .proto definitions are shared widely across many different components of the system, adding/removing required fields could easily bring down multiple parts of the system. We have seen production issues caused by this multiple times and it's pretty much banned everywhere inside Google for anyone to add/remove required fields. For this reason we completely removed required fields in proto3.

After the removal of "required", "optional" is just redundant so we removed "optional" as well.

**Comment by yzhao1012** [comment]
> After the removal of "required", "optional" is just redundant so we removed "optional" as well.

Note that removing optional does not mean that the "optionality" concept is gone.
The flaw of removing completely the optionality concept is more debatable, as often people want to have the old "has_<field>()" API for testing user intention.

**Comment by qia01ng** [comment]
> We dropped required fields in proto3 because required fields are generally considered harmful and violating protobuf's compatibility semantics. The whole idea of using protobuf is that it allows you to add/remove fields from your protocol definition while still being fully forward/backward compatible with newer/older binaries. Required fields break this though. You can never safely add a required field to a .proto definition, nor can you safely remove an existing required field because both of these actions break wire compatibility. For example, if you add a required field to a .proto definition, binaries built with the new definition won't be able to parse data serialized using the old definition because the required field is not present in old data. In a complex system where .proto definitions are shared widely across many different components of the system, adding/removing required fields could easily bring down multiple parts of the system. We have seen production issues caused by this multiple times and it's pretty much banned everywhere inside Google for anyone to add/remove required fields. For this reason we completely removed required fields in proto3.
> 
> After the removal of "required", "optional" is just redundant so we removed "optional" as well.

clearly.
