### ISSUE TITLE
[objectivec]what's the reason KeyedSubscript are not in the interface

### ISSUE THREAD

**Issue by aelam** [google/protobuf#2535]
I can find the two methods in the implementation file of GPBDictionary ( also I should find them in GPBArray but not)
 I don't know why it's not in the interface files 
```
- (id)objectForKeyedSubscript:(id)key;
- (void)setObject:(id)obj forKeyedSubscript:(id<NSCopying>)key;

```

**Comment by thomasvl** [comment]
Can you provide a code snippet for what's failing?  The keyedSubscript support is just in GPBAutocreatedDictionary to help bridge things over when it the field is would be an NSMutableDictionary.  NSArray shouldn't used keyedSubscript, it would be indexedSubscript, but I believe the default implementations will call through to the other methods that NSArray subclasses have to implement.

**Comment by thomasvl** [comment]
Finally got some time post holidays to circle back to this.

Re `GPBDictionary` - There are actually several classes defined there, the one you are looking at is an internal detail for the autocreator behavior \(more info in the [objectivec/README.md](https://github.com/google/protobuf/tree/master/objectivec#usage)\).  The overrides are just there for a minor performance improvement, things would work without it.  As far as why they aren't in the header, that class isn't in the header in general since it is an internal implementation detail.  Even if it was public, the methods don't need to be in the `@interface` block as the class is a subclass of `NSMutableDictionary` and thus the methods have already be declared there.

Re `GPBArray` - This also is a few specific classes for the different datatypes.  There also is a custom `NSMutableArray` subclass for autocreators, assuming that is the one you are asking about for indexedSubscript; those methods work without custom overrides because `NSArray`/`NSMutableArray` will channel the subscripting methods through to the methods subclasses have to implement, so there is no need to override anything.
