### ISSUE TITLE
JS compiler with one_output_file_per_input_file option

### ISSUE THREAD

**Issue by petehouston** [google/protobuf#2560]
I've had a look at the code at this line,

https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/js/js_generator.cc#L3230

here the part:
```
else if (options[i].first == "one_output_file_per_input_file") {
      if (!options[i].second.empty()) {   // <--- (*)
        *error = "Unexpected option value for one_output_file_per_input_file";  
        return false;
      }
      one_output_file_per_input_file = true;
    } 
```

Is the condition at `(*)` on purpose?

I want to compile all `.proto` files into one single file, then how can I achieve it?

**Comment by acozzette** [comment]
That conditional is intentional--the idea is just that some options are of the form `option=value` and others are just of the form `option`. That particular option doesn't take a value a so it would be invalid to try to say something like `one_output_file_per_input_file=whatever`.

I believe the `library` option [here](https://github.com/google/protobuf/blob/2deb139bc952fcc313803c4520e802dc1f6da9be/src/google/protobuf/compiler/js/js_generator.h#L112) should do what you want by allowing you to compile everything into a single .js file.

**Comment by petehouston** [comment]
@acozzette I see. Well, those two options, `library` and `one_output_file_per_input_file`, are kinda confused. Anyway, I just want to know if it is on purpose.

**Comment by acozzette** [comment]
@petehouston You're right, those two options are a bit confusing. Part of the reason for that is that at one time we had multiple JS implementations that had different ways of organizing their output and then we eventually unified them but had to keep both options around to preserve compatibility with the different implementations' quirks.
