### ISSUE TITLE
[2.6.1 - Cygwin/MinGW] Stuck at linking

### ISSUE THREAD

**Issue by ItachiSan** [google/protobuf#258]
As in title: I'm having a few problems compiling using MinGW-w64 toolchain under Cygwin.
Everything is fine untill the link of *libprotobuf.la*:
```
...
/bin/sh ../libtool  --tag=CXX   --mode=link x86_64-w64-mingw32-g++ -pthread -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -O2 -g -DNDEBUG -version-info 9:0:0 -export-dynamic -no-undefined  -o libprotobuf.la -rpath /usr/x86_64-w64-mingw32/sys-root/mingw/lib google/protobuf/stubs/atomicops_internals_x86_gcc.lo google/protobuf/stubs/atomicops_internals_x86_msvc.lo google/protobuf/stubs/common.lo google/protobuf/stubs/once.lo google/protobuf/stubs/stringprintf.lo google/protobuf/extension_set.lo google/protobuf/generated_message_util.lo google/protobuf/message_lite.lo google/protobuf/repeated_field.lo google/protobuf/wire_format_lite.lo google/protobuf/io/coded_stream.lo google/protobuf/io/zero_copy_stream.lo google/protobuf/io/zero_copy_stream_impl_lite.lo google/protobuf/stubs/strutil.lo google/protobuf/stubs/substitute.lo google/protobuf/stubs/structurally_valid.lo google/protobuf/descriptor.lo google/protobuf/descriptor.pb.lo google/protobuf/descriptor_database.lo google/protobuf/dynamic_message.lo google/protobuf/extension_set_heavy.lo google/protobuf/generated_message_reflection.lo google/protobuf/message.lo google/protobuf/reflection_ops.lo google/protobuf/service.lo google/protobuf/text_format.lo google/protobuf/unknown_field_set.lo google/protobuf/wire_format.lo google/protobuf/io/gzip_stream.lo google/protobuf/io/printer.lo google/protobuf/io/strtod.lo google/protobuf/io/tokenizer.lo google/protobuf/io/zero_copy_stream_impl.lo google/protobuf/compiler/importer.lo google/protobuf/compiler/parser.lo  -lz
```
It's almost half an hour I've been waiting.
Also, I setted **CC**/**CXX** in order to be *x86_64-w64-mingw32-***gcc**/**g++**
All I did was:
```
- downlod the zip source file, unpack it and get a Cygwin terminal there -
./autogen.sh
./configure --build=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw
make
```
Maybe other users had my same problem; just want to figure out how to finish compiling.
If you need some specific infos just tell me below.

**Comment by obfuscate** [comment]
This is a rather fragile build setup. At the onset, autogen.sh will likely (among other things) warn that AM_PROG_AR is required for this setup, so this may as well be added to configure.ac before doing anything else. I don't know why this isn't already being done, since the ifdef solution shouldn't cause any problems elsewhere.

If any absolute unix pathnames (such as the path for --prefix) are passed to libtool, it will hang indefinitely without any visible error. The func_convert_file_cygwin_to_w32 helper can convert these paths (see below). This should stop libtool from hanging, but the resulting protoc.exe binary will similarly refuse unix paths, although you at least get an error this time.

The `--with-protoc=protoc` configure option allows using the native protobuf's protoc.exe when cross-compiling, which will solve the latter problem, but protobuf (of the same version to be built for mingw) must be built/installed for the cygwin environment first.

### Building for x86_64-w64-mingw32

In configure.ac, where it checks for programs, add `m4_ifdef([AM_PROG_AR], [AM_PROG_AR])`

```bash
    # Use the mingw toolchain.
    export CC=x86_64-w64-mingw32-gcc
    export CXX=x86_64-w64-mingw32-g++

    # Prevent libtool from choking on unix paths.
    export lt_cv_to_host_file_cmd=func_convert_file_cygwin_to_w32
    export lt_cv_to_tool_file_cmd=func_convert_file_cygwin_to_w32

    # Use the native cygwin protoc.exe
    ./autogen.sh
    ./configure --build=x86_64-w64-mingw32 --with-protoc=protoc --prefix=/somepath
    make
    make check
    make install
```

To run the exe, the mingw gcc DLLs must be accessible via `PATH`, bundled with the exe, or statically linked, as usual.
