### ISSUE TITLE
Well known types for sint32 and sint64?

### ISSUE THREAD

**Issue by ajaybha** [google/protobuf#2603]
Hi,
The `wrappers.proto `contain well-known types for few primitive types but the ones for `sint `are missing. Given that the sint provides more efficient encoding for small numbers [https://developers.google.com/protocol-buffers/docs/encoding#signed-integers](url), I am wondering why the wrappers are not defined for them? 
 As per Issue#2575 [https://github.com/google/protobuf/issues/2575](url), google/Protobuf path need to be maintained for importing well-known types. Can we define wrapper types for `sint32 `and `sint64 `following the same convention & keep them under google/protobuf?

**Comment by acozzette** [comment]
One drawback of the wrappers is that they add at least two bytes of overhead on the wire, since they wrap the primitive field inside a submessage. So I think if you're concerned enough about wire size that you're using `sint32` or `sint64`, you would probably want to avoid using a wrapper in that case anyway. One thing you can do is have a `oneof` containing just a single primitive element; this makes the syntax slightly more awkward but will let you have a nullable `sint32` or `sint64` without the overhead of a wrapper.

**Comment by WarrenFerrell** [comment]
Think this is a bit of an oversight as the work required to add a new well-known-type is minimal and if a field requires nullability and is likely (or in our use case, guaranteed) to be a small negative number then SInt32Value can save you 9 bytes over Int32Value. The issue of an Option type is separate and doesn't prevent this from being implemented. But not adding SInt32Value does prevent libraries from providing special handling like they do for some other well known types.

**Comment by jschultz410** [comment]
Why was this issue closed?  If the whole point of wrappers.proto is to wrap the basic scalar types, then shouldn't it have wrappers for all the basic scalar types???

**Comment by AlexeiZenin** [comment]
I petition we remove all wrappers and only leave the `BytesValue` wrapper since you can place anything into the BytesValue wrapper, why support all the scalar types 😄
