### ISSUE TITLE
BUILD and protobuf.bzl shouldn't define targets not included in language-specific .zip

### ISSUE THREAD

**Issue by jmillikin** [google/protobuf#2721]
I'm trying to use the Bazel public docs to get a basic protobuf-enabled `py_binary` working. The builds worked fine, but the result would fail because descriptor.py wasn't included in the `.runfiles` dir. Here's the block of `WORKSPACE` that was incorrect:

```python
http_archive(
    name = "protobuf",
    url = "https://github.com/google/protobuf/releases/download/v3.2.0/protobuf-cpp-3.2.0.zip",
    strip_prefix = "protobuf-3.2.0",
)
```

The bug is that I set the url to `protobuf-cpp` instead of `protobuf-python`, so the `:python_srcs` target defined in `protobuf/BUILD` was valid but contained no files.

This would have been much easier to debug if `BUILD` or `protobuf.bzl` only contained targets for languages supported by the release archive, so Bazel would complain loudly if the user references the wrong url.

**Comment by TeBoring** [comment]
The problem is that protobuf-cpp-3.2.0.zip is for cpp only. We remove everything unrelated from the source before making the zip. Besides, we search python directory to find sources instead of explicitly listing everything: https://github.com/google/protobuf/blob/master/BUILD#L581
We don't want to change this to make maintaining complicate. Thanks for being considering.
