### ISSUE TITLE
Add --descriptor_set_in protoc option

### ISSUE THREAD

**Issue by rmichela** [google/protobuf#2725]
Protoc currently supports `--descriptor_set_out`. It would be great if it also supported `--descriptor_set_in`.

Using `--descriptor_set_in`, users could pipe pre-compiled protos directly into the standard code generation pipeline (c++, java, c#, and plugins). 

`--descriptor_set_in` really shines when coupled with the gRPC reflection service. This would allow a gRPC service client to be generated knowing only the host and port of the service. Taken a step further, a developer tool could iterate the contents of a service discovery registry to present the user with a catalog of services. The user could then pick a service and add a generated stub to their project with a single command.

**Comment by cgrushko** [comment]
This FR is also useful for proto support in Bazel: there's considerable complexity around passing the right arguments to proto-compiler, which can be simplified if `proto_library` was the only piece of code responsible for this.

Bazel has a class to create the arguments, but it isn't yet exposed to Skylark, and either way it won't be as elegant as passing descriptor sets.
(note that Bazel needs to pass multiple descriptor sets to protocol-compiler)

**Comment by cgrushko** [comment]
@xfxyjwf this becomes more important the more complicated `proto_library` becomes.
For example, right now `proto_library` performs direct-dependency checks, which further complicates the command-line it produces.

As more languages get their implementations for `LANG_proto_library`, it becomes more important to have all of them behave the same. 

I just had a conversation about `swift_proto_library`; if it's written by constructing the command-line directly from the `.proto` sources, there's a good chance it'll miss enforcing direct dependencies.
This means that in a multi-language repo, a commit from a Swift developer could break other language builds.

**Comment by xfxyjwf** [comment]
For protoc command line flags, `protoc --help` is likely the best place of documentation. It has this to say for `--descriptor_set_in` right now:
```
  --descriptor_set_in=FILES   Specifies a delimited list of FILES
                              each containing a FileDescriptorSet (a
                              protocol buffer defined in descriptor.proto).
                              The FileDescriptor for each of the PROTO_FILES
                              provided will be loaded from these
                              FileDescriptorSets. If a FileDescriptor
                              appears multiple times, the first occurrence
                              will be used.
```
If you find it unclear, feel free to ask questions or send us pull requests.

**Comment by lukesneeringer** [comment]
How does this actually work? If I run `protoc --descriptor_set_in={path to descriptor}` with some set of `*_out` options, I get an error complaining that I did not specify a proto file.

**Comment by xfxyjwf** [comment]
You still specify the files you want to generate code for normally. For example:
```bash
$ protoc --descriptor_set_int=/path/to/descriptors --cpp_out=. google/protobuf/descriptor.proto
```

**Comment by acozzette** [comment]
The descriptors are more-or-less just a machine-friendly representation of the human-friendly .proto file. (The descriptors are themselves proto messages and can thus be serialized just like other protos.) You can indeed use the `--descriptor_set_out` and `--descriptor_set_in` options as a way to parse the definitions just once and then invoke `protoc` multiple times on the resulting descriptors.

**Comment by davidgiven** [comment]
That's what I expected, but I haven't been able to make this work. If I don't pass in at least one `.proto` file on the command line, I get an error about missing input files. This applies to both `--cpp_out=` and `--encode`. The only workaround I've found is to pass the entire set of `.proto` files in on every invocation.

**Comment by acozzette** [comment]
I believe you just need to give it the name of the .proto file you want to generate code for, and it will look up that name in the descriptor set. It still needs this because otherwise it can't know what .proto file you want to generate code for--in general the descriptor set may contain many files but you wouldn't necessarily want to generate code for all of them at once.

**Comment by davidgiven** [comment]
So I've just run into this problem again and hey look I seem to have commented on this before...

I made this work this time! But it's not intuitive. For `--encode` you need to pass in both the name of the message type being encoded, and also the filename of the proto source file. This appears to be looked up in the descriptors. This really surprised me, as surely the message can be found from the type name passed in as the parameter to `--encode`?

This is rather awkward when using compiled protos as (at least in bazel) as once you've generated the proto library, the filenames aren't available in the build system any more. The consumer of the proto library shouldn't need to know about the filenames of the source files inside the proto library, IMO.

**Comment by acozzette** [comment]
I think the tricky thing here is that if we're working with serialized descriptors then we could potentially get away with omitting the file name, but that would not work well in the case where we're reading proto files from the filesystem. In that case we would have to open up every file in the search path that looks like a proto file until we're able to find the right one, and this would get messy. So I think it's probably best to keep the `--encode` behavior consistent whether we're reading proto files or serialized descriptors.

In the case of Bazel we could potentially provide a rule that works around this, though. We actually have an internal rule that does this, but it would be hard to directly open source because it depends on various other internal-only things. It wouldn't be that hard to write a simple binary that takes in a text proto and a descriptor set and transcodes the text to binary, though, along with a Starlark rule that invokes this binary.

**Comment by ascopes** [comment]
On this feature, the documentation specifies that the argument takes a delimited collection of files, but doesn't specify what the delimiter actually is...

I am working on https://github.com/ascopes/protobuf-maven-plugin/pull/629 to provide Maven support for this feature... is there anywhere that documents this?

**Comment by davidgiven** [comment]
I just ran into that myself (I may have filed a bug, I've forgotten). I could not find any documentation for it and just had to try different ones until something worked. For the record, it's a colon.

**Comment by ascopes** [comment]
@davidgiven from what I can tell, having gone through the source code, it uses the system path separator, so `:` on Linux and macOS, and then `;` I assume on Windows. I haven't had time to test on Windows just yet though.

Would be good if this was mentioned in the `--help` page (happy to raise a PR if we can get the behaviour confirmed).

**Comment by davidgiven** [comment]
@ascopes I wasn't aware of that --- that's not optimal... changing the flag so that multiple invocations accumulated entries rather than replacing the previous entry would make this easier; would there be any interest in a trivial PR?

**Comment by ascopes** [comment]
@davidgiven I can try to take a look when I have some time (possibly at the weekend). Will need to get my machine set up to build the C++ project first since I'm not too familiar with the process in place.

I assume we wouldn't consider passing more than one --descriptor_set_in to be a breaking change, since it would only alter the behaviour for users that are relying on broken/undefined behaviour passing it more than once in the first place?

**Comment by davidgiven** [comment]
@ascopes Don't worry, I'll take a look myself (given I was the one who asked for it)!
