### ISSUE TITLE
How to decode Bytes field to binary String instead of Base64 String in the Ruby parser?

### ISSUE THREAD

**Issue by minor6th** [google/protobuf#2801]
When I call to_json on a message in Ruby, the Bytes fields in the message is converted to a Base64 String, which I have to manually convert back to a binary string.

**Comment by acozzette** [comment]
This behavior is actually to be expected, because `bytes` fields (unlike `string` fields) can contain non-UTF8 binary data, and since that cannot be directly represented in JSON, we have to base64-encode it.

**Comment by mykiimike** [comment]
Hi there,

Sorry to reopen the subject but I still don't understand this base64 encoding story. Whether it is in JS or another language, bytes must be represented in an array of uint8. Now, going back to normal behavior would break the ABI, it's a shame. It would be useful to have at least one option to change the management of bytes in an array. 
  
All the best
Michael

**Comment by acozzette** [comment]
@mykiimike I don't think we really have much of a choice here, because we're constrained by the fact that JSON strings must be UTF-8. As a result we can't put a raw `bytes` field directly in a JSON string without encoding it in base64 or similar. That would result in invalid JSON (unless the bytes coincidentally happen to be valid UTF-8).

**Comment by mykiimike** [comment]
Just for testing
```js
jspb.Message.bytesAsB64 = function (value) {
    if (value == null || value instanceof Uint8Array || typeof value === 'string') {
        return value;
    }
    goog.asserts.fail('Cannot coerce to b64 string: ' + goog.typeOf(value));
    return null;
};

[...]

console.log(JSON.stringify(message.toObject()))
```


And got 
```
"hash":{"type":"Buffer","data":[30,148,33,70,51,43,61,77,127,198,61,187,50,199,224,181,100,123,84,182,83,102,68,68,224,205,69,83,140,104,146,34]}
````

Which is actually correct and respect the utf8 encoding (or whatever)

The problem occurs when you deserialize data and do a toObject() on it. It will be wrong like that 
```
"hash":{"0":100,"1":36,"2":4,"3":26,"4":73,"5":80,"6":183,"7":164,"8":49,"9":213,"10":181,"11":49,"12":185,"13":143,"14":155,"15":23,"16":103,"17":243,"18":213,"19":127,"20":56,"21":221,"22":23,"23":110,"24":36,"25":250,"26":202,"27":44,"28":37,"29":153,"30":58,"31":242}
```

This is due because of using Uint8Array internaly in JSPB.

I think the best is to add a Buffer management for JSPB as supported in JSON stringify

**Comment by acozzette** [comment]
Unfortunately JSPB does not support the proto3 JSON format. The `toObject()` method returns something which looks similar to proto3 JSON but is not quite the same thing.

**Comment by mykiimike** [comment]
Yes, I understood that you can't change that without affecting compatibility. Maybe in proto4 then :) 

On the other hand I can assure you that in a future version it would be possible without B64 encoding ,)

**Comment by acozzette** [comment]
I think I see what you mean now; if we were to use an array of ints then that would work and would remove the need for base64. Base64 might still have some advantages--smaller wire size and perhaps faster to decode, but you are right that in any case we can't change it now since we have to maintain compatibility.

**Comment by mykiimike** [comment]
> Base64 might still have some advantages--smaller wire size

I agree but that's not the purpose because the JSON memory is (generally) transitional in PB, we shouldn't have to store it in this state.

> perhaps faster to decode

I'm less sure because B64 requires some rotation & branching in addition to parsing. To tell the truth, I think the performance benefit would be quite significant without B64. We can measure it :)

**Comment by acozzette** [comment]
I'd have to think about it some more but intuitively it seems to me like base64 would be easier to parse efficiently. It should be more predictable because four bytes of input leads to exactly three bytes of output, whereas if you're parsing decimal ints then each byte of output corresponds to a variable-sized input (between one and three bytes). I would expect it to be harder for the CPU to speculatively scan ahead because you can't know in advance where the next element begins.
