### ISSUE TITLE
Will there be javascript support for parsing text format messages?

### ISSUE THREAD

**Issue by phubner** [google/protobuf#2805]
Currently in the C++ code base you can read/parse textformat style messages. `google::protobuf::TextFormat::Parse` However I do not see this capability in the javascript base. I was just wondering if this is something that will be added?

**Comment by acozzette** [comment]
No, right now we don't have any plans to add text-format support for JavaScript. That feature could be nice to have, but since it's mostly used for development and debugging it would be a low priority for us to implement. If you have something like configuration data you're thinking of storing in text format, I would recommend possibly just storing it in the main binary format and using `protoc --decode` when you need a quick way to convert it to a human-readable form.
