### ISSUE TITLE
Calling getFieldBuilder() for an extension causes NPE in Java

### ISSUE THREAD

**Issue by blexim** [google/protobuf#2813]
When building a proto message that has extensions, if I try to get a builder for a field that is an extension using the reflection function getFieldBuilder(), I get a null pointer exception. I'm seeing this in protobuf 3.2.0. I've tried to work around this, but haven't been able to find a way that gives me nested builders. Small repro case:

extend.proto:
```
syntax = "proto2";
package foo;
option java_outer_classname = "ExtendProto";

message A {
  extensions 1 to 10;
}

message B {
  extend A {
    optional B b = 1;
  }
}
```

TestBuilder.java:
```
import foo.ExtendProto.A;
import com.google.protobuf.Descriptors.FieldDescriptor;

public class TestBuilder {
  public static void main(String[] args) {
    A.Builder builder = A.newBuilder();
    FieldDescriptor bDescriptor = builder.getDescriptorForType()
      .findFieldByNumber(1);
    builder.getFieldBuilder(bDescriptor);
  }
}
```

Output:
```
$ java -cp ~/Downloads/protobuf-java-3.2.0.jar:. TestBuilder 
Exception in thread "main" java.lang.NullPointerException
	at com.google.protobuf.GeneratedMessage$FieldAccessorTable.getField(GeneratedMessage.java:2139)
	at com.google.protobuf.GeneratedMessage$FieldAccessorTable.access$200(GeneratedMessage.java:2021)
	at com.google.protobuf.GeneratedMessage$Builder.getFieldBuilder(GeneratedMessage.java:523)
	at TestBuilder.main(TestBuilder.java:9)
```

I believe the cause is `getFieldBuilder` missing from the `ExtendableBuilder` interface.

**Comment by xfxyjwf** [comment]
I tried your sample code and found that the NullPointerException is actually because of the bDescriptor being null, i.e., you haven't actually gotten the right extension descriptor. To get the descriptor for the extension, you need to do this instead:

```java
FieldDescriptor bDescriptor = B.getDescriptor().getExtensions().get(0);
```

You need to get it from `B` because the extension is defined in the scope of `B`.

After that you will still get an exception if you try to call getFieldBuilder() on the descriptor. That's because field builder is not supported for extensions. You will instead need to do it like this:

```java
FieldDescriptor bDescriptor = B.getDescriptor().getExtensions().get(0);
Builder subBuilder = ((Message) builder.getField(bDescriptor)).toBuilder();
...  // use subBuilder
builder.setField(bDescriptor, subBuilder.build());
```
