### ISSUE TITLE
Deterministic serialization

### ISSUE THREAD

**Issue by adam-26** [google/protobuf#2830]
Hi,

I am trying to determine what (if any) programming languages serialize protobuf models deterministically?

Based on my understanding of the protobuf format all `map` types must be sorted lexically bytewise using the `key` value for serialization, if a model to be serialized deterministically.

I have had a look at some source code, it appears that the [javascript implementation](https://github.com/google/protobuf/blob/7f3e23707122f31ebfa58b7280bd56cbe77cb44e/js/map.js#L426) is serialized deterministically, is this correct?

#1937  would suggest that the Java implementation does not currently serialize deterministically.

I couldn't find any documentation on this, does a document exist that indicates what languages serialize deterministically?

Thanks, Adam.

**Comment by acozzette** [comment]
The way this works is that map fields are ordinarily serialized in an arbitrary order, but for C++ and Java we have APIs to provide deterministic serialization (and thus sorting of maps) if you need that feature:
- C++: https://github.com/google/protobuf/blob/a1bb147e96b6f74db6cdf3c3fcb00492472dbbfa/src/google/protobuf/io/coded_stream.h#L834
- Java: https://github.com/google/protobuf/blob/a1bb147e96b6f74db6cdf3c3fcb00492472dbbfa/java/core/src/main/java/com/google/protobuf/CodedOutputStream.java#L159

One thing to note is that these APIs give you serialization that is deterministic for a single executable, but not necessarily stable across multiple builds. So if you need some kind of identifier that will be stable for a long time, it's best to create your own format rather than trying to rely on deterministic proto serialization.

That's interesting that you point out that the JavaScript implementation always sorts its maps. I think this is actually a bug we should fix, because it's confusing that it does something different from the other implementations, and on top of that we would probably get better performance by skipping the unnecessary sorting. I'll try and see if it's feasible to remove the sorting there.

**Comment by adam-26** [comment]
Thanks for the info @acozzette.

I do require an identifier that will remain stable across builds and multiple programming languages. To ensure I correctly understand how to achieve this, can you confirm first that a message without any map fields will always be serialized deterministically across all programming languages?

Can you elaborate on what has/may change between builds that prevents the deterministic serialization of fields from being stable? And does this relate only to map fields, or can this apply to other fields also (assuming the same proto version across builds)? How does this impact serialization/deserialization between different programming languages?

Sorry for all the questions, just need to ensure I can create a stable identifier thats reliable and correct.

Thanks again, Adam.

**Comment by acozzette** [comment]
Even without map fields, at the moment you might technically be able to get the same serialized bytes for the same proto across builds and languages, but it would probably not be a good idea to rely on this. The main reason is that we want to have the option of evolving the format over time, and if code starts relying on the serialized bytes remaining 100% identical then we can no longer do that. For example, our serializers generally produce their output sorted by field number, but this is not a requirement and parsers have no problem parsing unsorted input. We could potentially find a good reason to stop serializing in sorted order and if that ever happens then code that uses the serialized bytes as an identifier would break.

The other issue is unknown fields. You can canonicalize map fields by sorting their entries, but only if you know where the map fields are; if you have an unknown field that contains map data then there's no way to canonicalize the maps. So this is one reason the serialized output can change from one build to the next. One build might see an unknown field and leave it alone, while the next build has an updated schema and changes the output because it knows that this field contains a map.

None of this affects compatibility between languages; you can always serialize a message in one language and parse it back from another.

I hope that makes sense, let me know if you have any other questions.

**Comment by adam-26** [comment]
Thanks for the details response, that answers all my questions :)
