### ISSUE TITLE
Language Guide assumes Proto3

### ISSUE THREAD

**Issue by cconroy** [google/protobuf#286]
The language guide at https://developers.google.com/protocol-buffers/docs/proto#oneof assumes that users are on version 3, but it doesn't call this out explicitly.

There should be a different language guide for each major version. Or, at the very least, the new features in version 3 should be called out explicitly.

**Comment by xfxyjwf** [comment]
What makes you think that way? oneof is a feature included in proto2 as well.

We'll update the developer guide with a separate page for proto3 soon. The current page is intended to cover proto2 features.

**Comment by cconroy** [comment]
maps are specific to proto3, are they not?

oneof is in proto2, but only as of proto2.6

**Comment by cfallin** [comment]
Map fields also work in proto2.

Since you mention 2.6, I think there may be some confusion as to the different version numbers floating around: when we say "proto3", we mean the proto3 syntax and set of semantics, which are selected by indicating `syntax = "proto3"` at the top of the `.proto` file. Similarly "proto2" means the semantics and features selected by `syntax = "proto2"` at the top of the file. This syntax/semantics version is distinct from the protobuf package release version, which is currently 3.0.0-alpha-2 (although it is not independent, as syntax/semantics version proto3 is only supported in release version >= 3).

So map fields are available only in recent releases, but work fine with syntax/semantics level `proto2`.

**Comment by cconroy** [comment]
@cfallin Thanks for the clarification. I think there's still an issue here because there are a few axes.

proto2 is wire compatible with all 2.x versions

However, protoc language support varies across 2.x versions. The guide should tag the protoc version necessary for each feature (e.g. >=2.6.0 for oneof)

**Comment by haberman** [comment]
All of these features are very old now. Protobuf 3.x has been out for over six months. I don't think changing the documentation at this point would be worth the effort.

**Comment by zoller27osu** [comment]
@haberman you still have to go out of your way to get a protoc version higher than 2.6.1 in many circles, including Ubuntu versions before 16.10 and **Google's own workstations**. I don't know about anyone else, but I often try to use backported features in Google internal code and can't because protoc doesn't understand them. IMO this is still a very big issue until protoc versions less than 3 are completely out of circulation.
