### ISSUE TITLE
Why implement GetCurrentTime with nanos always 0?

### ISSUE THREAD

**Issue by Wsine** [google/protobuf#2886]
See [here](https://github.com/google/protobuf/blob/master/src/google/protobuf/stubs/time.cc#L268)

```
void GetCurrentTime(int64* seconds, int32* nanos) {
  // TODO(xiaofeng): Improve the accuracy of this implementation (or just
  // remove this method from protobuf).
  *seconds = time(NULL);
  *nanos = 0;
}
```

**Comment by j3parker** [comment]
The `nanos` field is part of the `Timestamp` [message](https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/src/google/protobuf/timestamp.proto#L107) because it may be handy for implementations of that proto to provide that level of accuracy.

The `time` function [typically returns an integral number of seconds](http://en.cppreference.com/w/cpp/chrono/c/time) so it's most accurate to use 0 for `nanos`.

If you have a higher-resolution clock you can just avoid using this helper method and set `seconds`/`nanos` directly.
