### ISSUE TITLE
AttributeError: 'module' object has no attribute 'text_format' 

### ISSUE THREAD

**Issue by Bonsen** [google/protobuf#2903]
import google.protobuf as pb2
pb2.text_format    (error)
pb2.text_format.Merge    (error)

import google.protobuf.text_format  is fine

I find my version is '3.2.0'..

**Comment by pherl** [comment]
Can you try if you can refer to other modules under google.protobuf? This is usually caused conflicts with a previous installed version. Can you use virtualenv and have a clean protobuf python install?

**Comment by arthur-tacca** [comment]
This is because that original code snippet *shouldn't* work. But presumably you filed the bug because it did seem to work at some point in the past. Just for future reference, this is how this error can arise.

I believe that the root cause is that in the past you were (unwittingly) using some dependency that had been importing `google.protobuf.text_format`. So long as that other library is imported before you import `google.protobuf`, your code will work by accident:

    # in some_other_library:
    from google.protobuf import text_format  # Imported the proper way
    # import google.protobuf.text_format would also work fine
    
    # in your code:
    import some_other_library
    import google.protobuf     # Doesn't mention text_format!
    t = google.protobuf.text_format  # works by accident

But if the other library removes its import, or you move the import of that library after your import of `google.protbuf`, then your code will break:

    # in some_other_library:
    from google.protobuf import json_format  # Switched to using JSON
    
    # in your code:
    import some_other_library
    import google.protobuf     # Doesn't mention text_format!
    t = google.protobuf.text_format  # throws AttributeError
