### ISSUE TITLE
parseFromData   the server response Data   run  GPBCodedInputStream.m  wrong

### ISSUE THREAD

**Issue by anker-eric** [google/protobuf#2909]
rror Domain=GPBCodedInputStreamErrorDomain Code=-103 "(null)" UserInfo={Reason=Unexpected tag read}

**Comment by thomasvl** [comment]
You're likely going to have to give us more information for what you think was wrong and why.  Can you provide an example showing the protos and binary data that is triggering this?

**Comment by HermioneHu** [comment]
![b8998126-aea1-4413-8b7d-d33f36dc9a46](https://cloud.githubusercontent.com/assets/16183401/25882267/df4e87e4-3574-11e7-920b-71e465f31d7e.png)
I have the same issue.
I'm using Protobuf 3.2 version.The error as the picture you see, this happens when I get the data from the backward and I parse the data.pls help to have a look the error! Reply if you need more information!

**Comment by thomasvl** [comment]
We'd need to see the actually binary blob and the proto definition(s) to figure out what is happening.  Otherwise about all I can tell you is the blob doesn't match what you are trying to parse it as; either a group didn't end correctly, it contained a MessageSet and that didn't parse correctly, or message otherwise ended incorrectly.

**Comment by HermioneHu** [comment]
Thank you for your sincere and immediate reply. 
I have already solved the problem with my backend colleagues several days ago.The problem is just as you said.When my colleagues review their code and fix the error, I can receive the binary data normally.

**Comment by zzialx** [comment]
Domain = GPBCodedInputStreamErrorDomain Code = -103“（null）”
I encountered this problem that cannot be resolved, this is the binary stream that the server gave me, I cannot parse.

stream：
<0000002d 80000001 000003e9 221f0801 68017a09 31323334 35363738 39820106 31323334 35369001 019a0101 32>

**Comment by thomasvl** [comment]
@zzialx You need to check with your severs folks as to what format they are using.  The leading `0000002d` really looks like a length on the front, as the rest of the data is 45 bytes.  So this might not be expected to be a "plain" protobuf binary, but instead has some custom framing on it.
