### ISSUE TITLE
Where is sys/param.h file?

### ISSUE THREAD

**Issue by AjeyaGupta** [google/protobuf#2940]
I am using GreenHills compiler to compile the .pb.h, .pb.c and other .cc files. When I first compiled, it showed me an error saying "Fatal Error #5, cannot enter common.h".  I had to change the directory of common.h in addressbook.pb.h file in its #include statement. By doing this, I got rid of this error and was able to enter in common.h file. I did similar thing to port.h which is in common.h file. However, in port.h, its now showing me error on line 62, saying "cannot enter sys/param.h". I thought of changing the path for this part of the code, but I am not able to fine this particular file i.e. param.h in any directory. Hence, I am not able to proceed further.

Any help regarding this "sys/paramh.h" will be appreciated.

Thank You

**Comment by acozzette** [comment]
The sys/param.h header is just a system header like stdio.h. On my system its full path is /usr/include/sys/param.h. What OS are you using?

**Comment by AjeyaGupta** [comment]
Thanks for your reply Adam. I am using Windows OS and GreenHills compiler

**Comment by acozzette** [comment]
Ok, I think what's going on is that we have some #ifdefs that try to avoid pulling in that header when building for Windows: https://github.com/google/protobuf/blob/69bfde22b6eb9effd84f7d554b565285e62c0824/src/google/protobuf/stubs/port.h#L50
https://github.com/google/protobuf/blob/69bfde22b6eb9effd84f7d554b565285e62c0824/src/google/protobuf/io/coded_stream.h#L116
But perhaps because you're using the GreenHills compiler, the `_WIN32` and `_MSC_VER` macros we check for are not defined even though you're actually building on Windows. So to get around this, you could either try to figure out a way of tweaking the #ifdefs so that they work for the GreenHills compiler, or else just locally edit the source code so that you can get your build working.

**Comment by AjeyaGupta** [comment]
Yes, that's what I did today in the morning. I somehow tweaked the source code (specifically the ifdef part and _WIN32 part) and got rid of the errors. But, it looks like I am getting a complete set of new errors. Starting with "# not expected here: GOOGLE_PROTOBUF_PLATFORM_ERROR" in platform_macros.h. This along with 100 other errors.. :-(

**Comment by vamp89** [comment]
I know it is old but how did you manage to solve the "# not expected here: GOOGLE_PROTOBUF_PLATFORM_ERROR" in platform_macros.h
Thanks
