### ISSUE TITLE
JavaScript: expose BinaryEncoder

### ISSUE THREAD

**Issue by jakubka** [google/protobuf#2970]
We have something like a custom protocol based on Protobuf and being able to use [`BinaryEncoder`](https://github.com/google/protobuf/blob/master/js/binary/encoder.js) when creating messages would be extremely helpful.

It is a nicely self contained class, which might be worth exposing to let people use it in scenarios like ours. Would you consider it?

**Comment by acozzette** [comment]
@jakubka I think we would hesitate to make it part of the public API, just because then it becomes an interface that we have to maintain and we would have to worry about breaking backward compatibility when we do refactorings. In your case would it be an option to just make your own private copy of the BinaryEncoder class?

**Comment by jakubka** [comment]
@acozzette thanks for getting back to me, makes sense. Yep, I've already copied specific bits and pieces which are useful for us. 👍
