### ISSUE TITLE
protoc order of ipaths results in different directory structure

### ISSUE THREAD

**Issue by btuysser** [google/protobuf#3044]
When using messages defined in sub-directories the protobuf compiler (3.2.0) will generate a  different structure based on the order of ipaths entered. 

Assume the following structure : 

/root_dir/root.proto
/root_dir/foo_dir/foo.proto

1.) 
protoc --cpp_out /dest_dir **-I /root_dir** -I /root_dir/foo_dir/ /root_dir/root.proto
protoc --cpp_out /dest_dir **-I /root_dir** -I /root_dir/foo_dir/ /root_dir/foo_dir/foo_file.proto

results in  : 

/dest_dir/root.pb.[cc|h]
/dest_dir/**foo_dir**/foo_file.bp.[cc|h]

2.) 
protoc --cpp_out <somewhere> -I /root_dir/foo_dir/ **-I /root_dir**  /root_dir/root.proto
protoc --cpp_out <somewhere> -I /root_dir/foo_dir/ **-I /root_dir**  /root_dir/foo_dir/foo_file.proto

results in  : 

/dest_dir/root.pb.[cc|h]
/dest_dir/foo_file.bp.[cc|h]

This causes PROTO_SRC/HDR in protobuf_generate_cpp to be wrong for 1.) Please find attached a quick cmake project illustrating the issue. 

1.) tar -zxf protoc_issue.tgz
2.) cd protoc_issue/build
3.) cmake ..; make
[protoc_issue.zip](https://github.com/google/protobuf/files/972255/protoc_issue.zip)

**Comment by xfxyjwf** [comment]
This is sort of working as intended. Not only the output file path will be different depending on the "-I" flag, the actual content of the generated file will also be different. It works this way because protoc uses the "-I" flag along with the file path to determine an unique import name for each .proto file. For example,
```bash
protoc -I /root_dir /root_dir/foo_dir/foo_file.proto
```
In the above example, the .proto file has an unique import name as "foo_dir/foo_file.proto".
```bash
protoc -I /root_dir/foo_dir /root_dir/foo_dir/foo_file.proto
```
In this example, the .proto file's import name is "foo_file.proto".

This import name is used by the "import" statement and is also the file name if you are to look up its descriptor in protobuf global descriptor pool. As such, you need to make sure the same file always have the same import name across different protoc invocations.

At the moment, the import name is determined by matching the "-I" import path as a prefix of the .proto file path. As such if you happen to have multiple "-I" import path that are prefixes of the .proto file path, order of these "-I" will matter because the matching process is done in command-line order.

The only fix I can think of is the make the matching process match the longest import path first so in your case, /root_dir/foo_dir/foo_file.proto will always be matched to "-I /root_dir/foo_dir", but that's a behavior change and will likely break some users who rely on the current behavior.

**Comment by btuysser** [comment]
It seems to me that more options would resolve the overloading of the Ipath when it comes to determining the import name? I assume something like -r <root_dir> would allow for deterministic import names across multiple protoc invocations without changing current behavior!? 

At the very least the current behavior this should be documented in --help to limit the confusion!?
