### ISSUE TITLE
Add bytes_value (and possibly others) to the struct.Value well-known-type proto.

### ISSUE THREAD

**Issue by mishas** [google/protobuf#3078]
google/protobuf/struct.proto defines the Value message, which can represent only values of type NullValue, double, string, bool, Struct or ListValue. It would be very helpful to have a bytes option as well.

This is especially useful when using the Value message in tandem with the ListValue message, and even more so with the map<> feature.

For example, in the following proto:
```
message MyMessage {
    map<string, struct.ListValue> my_map = 1;  // Map from string to a list of strings.
}
```
The generated python code for this gives a very nice syntax:
```
mm = my_pb2.MyMessage(my_map = {"a": ["1", "2", "3"], "b": ["4", "5", "6"]})
```

This can also be done with lists of numbers (although they'll be always coded as double), and with booleans, but can not be done with bytes.

**Comment by jhump** [comment]
@mishas, FWIW, `google.protobuf.BytesValue` does already exist, but it is in `google/protobuf/wrappers.proto`.

Sadly, the `google/protobuf/struct.proto` file really should be renamed `google/protobuf/json.proto` because it purely for translating JSON to proto. A `google.protobuf.Value` is a JS value, which is why the options are so limited and do not match proto's own scalar types (not even distinguishing between floating-point and integer values, 32-bit and 64-bit, or signed and unsigned integer types).

To fully represent an arbitrary protobuf message using a generic "struct" message, you'd need to create your own `Value`, `ListValue`, and `Struct` instead of using these well-known types.

**Comment by xfxyjwf** [comment]
The types in struct.proto is designed to represent JSON values but "bytes" is not an standard JSON value type so it won't be in struct.proto. You should use a string (base64 encoded maybe) instead.
