### ISSUE TITLE
HHVM Incompatibility: Can't use function call result as array base in write context

### ISSUE THREAD

**Issue by RyanGordon** [google/protobuf#3224]
The following line of code produces a fatal error when run with HHVM: https://github.com/google/protobuf/blob/6f325805c0bc956f927b0e2dbfb4dd8133b4ed69/php/src/Google/Protobuf/descriptor.php#L84

```
$file->getEnumType()[] =
                $file->addEnumType(
                    EnumDescriptor::buildFromProto(
                        $enum_proto,
                        $proto,
                        ""));
```

The error message: `Fatal error: Can't use function call result as array base in write context in /google/protobuf/php/src/Google/Protobuf/descriptor.php on line 84`

The fix is to switch it to:

```
$file->addEnumType(
                $file->addEnumType(
                    EnumDescriptor::buildFromProto(
                        $enum_proto,
                        $proto,
                        "")));
```

**Comment by michaelbausor** [comment]
It looks like this also affects multiple places in https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php, such as https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L536 and https://github.com/google/protobuf/blob/master/php/src/Google/Protobuf/Internal/Message.php#L549.

"HHVM not tested" is listed in the [Known Issues](https://github.com/google/protobuf/tree/master/php#known-issues) section - is the intention to support HHVM?

**Comment by RyanGordon** [comment]
Ah, good catch! I hadn't hit those code paths yet in my testing. I am currently working to port over the gRPC extension to HHVM. Both gRPC and this package is required by the PHP Cloud Spanner 
Library which I am working on using on HHVM.

Even if you choose to not officially support HHVM after this, I can still provide regular patches where needed. For the most part HHVM is language parity with PHP so changes required should always be kept minimal

I'll update this PR to address the 3 other places you found

**Comment by michaelbausor** [comment]
No worries. If you are also interested in getting tests to pass, you may have some additional work to do as well. Running `grep -r "()\["` from the `php` directory turns up a lot of results - some of which are fine because they are not assignments, but some of which may also cause problems.

Very cool to hear that you are working on Spanner! We have a PHP Spanner client lib in google-cloud-php here: https://github.com/GoogleCloudPlatform/google-cloud-php/tree/master/src/Spanner
and we are currently in the process of migrating google-cloud-php to start using the official PHP protobuf implementation.

**Comment by RyanGordon** [comment]
Ah yes, I believe I found and fixed all the non-test places. How does this approach look? 7e60055bcaed1edafd0b8edf86a029c276445f30

I'm looking at the tests and I see both https://github.com/google/protobuf/blob/master/php/tests/test_util.php and https://github.com/google/protobuf/blob/master/php/tests/generated_class_test.php
I'm not sure if I can update the second one since that one is generated, right?

I am indeed working on using the official PHP Spanner Client; However, I thought the Spanner client already used the official PHP protobuf implementation though? What are the differences between what it's using right now and what it will be using?

**Comment by TeBoring** [comment]
- I think, in test code, there are a lot of place using returned value as array base. Instead of adding a new function, can we divide the code to two lines (one to assign the return value to a variable, the other to use the variable as an array)?
- generated_class_test is test for generated class (it's not generated). I think you can change it the same as other files.

- Could you point me to Spanner's repository to see which they are using?

**Comment by michaelbausor** [comment]
@TeBoring The Spanner client library is here: https://github.com/GoogleCloudPlatform/google-cloud-php/tree/master/src/Spanner

Right now all google-cloud-php APIs that use gRPC are using a community-developed PHP protobuf implementation, and the intention is to migrate away from that ASAP. For APIs such as Spanner, Logging and Pubsub, there will be no change for users, because the protobuf implementation does not directly expose in the handwritten client (e.g. https://github.com/GoogleCloudPlatform/google-cloud-php/blob/master/src/Spanner/SpannerClient.php).

**Comment by RyanGordon** [comment]
@michaelbausor Is that the `DrSlump/Protobuf-PHP` library that is being replaced by this repository fully?

@TeBoring I see, I'll go through and make those updates as well

**Comment by michaelbausor** [comment]
@RyanGordon Yes, that is correct - we currently depend on https://github.com/stanley-cheung/Protobuf-PHP (see , but that dependency will be replaced by this repository.

**Comment by RyanGordon** [comment]
This is now fixed with: https://github.com/google/protobuf/pull/3225
