### ISSUE TITLE
The fundamental difference between PB and FB is what ?

### ISSUE THREAD

**Issue by zhangminglei** [google/protobuf#3296]
Please see here : https://github.com/google/flatbuffers/issues/4372. Thanks.

**Comment by xfxyjwf** [comment]
The fundamental difference is that protobuf's in-memory representation and wire format are separate, whereas FlatBuffer use the same representation for it's in-memory layout and wire format.

This means:
1. Protobuf has to do explicit parsing and serialization to convert between the in-memory representation and wire format, while FlatBuffer doesn't need these. When you build a FlatBuffer object in memory, you are actually serializing it at the same time.
2. FlatBuffer is more performant in parsing as it doesn't require conversion between two representations, but at the same time its in-memory layout also lacks flexibility (impossible or very inefficient to mutate a FlatBuffer object in memory) compared to protobuf. In a complex system protobuf is used as much as a data modeling language as a serialization format and it can be very hard to migrate to FlatBuffer.
3. FlatBuffer's wire format is not as compact as protobuf (FlatBuffer payload can be several times larger than protobuf payload). If you need to compress the payload before sending it over the wire, FlatBuffer might not provide any advantage due to its larger payload size.

As a side note we protobuf-team are investigating a new wire format for protobuf which we hope can provide much faster mapping from/to in-memory representation.

**Comment by zhangminglei** [comment]
Yep, Yep. We literally get the point. And I watched FlatBuffer's wire format, Many many ```0000``` ```0000``` ```0000``` ```0000```  representations as it writes to an output stream and that was really occupy a lot of disk space. BUT that is why FlatBuffers is so fast as it has a same representation for it's in-memory layout and wire format. For PB, needs unparsing and de-serialization when read data from an output stream or a byte array. Anyway, thank you so much and I am looking forward to **Protobuf team** are investigating a new wire format for it and it will be an awesome stuff I would say. BTW, I would suggest **Flatbuffers team** do a compressed API interface in a way if it is really necessary when doing a **RPC** stuff.

**Comment by ronniekan1127** [comment]
Accessable Rich Internet…?

**Comment by chenliu0831** [comment]
@ericsalo curious if you know any progress / availability on below?

> As a side note we protobuf-team are investigating a new wire format for protobuf which we hope can provide much faster mapping from/to in-memory representation.

**Comment by ericsalo** [comment]
I have no idea what this means. Whence comes this claim?

**Comment by chenliu0831** [comment]
It comes from https://github.com/protocolbuffers/protobuf/issues/3296#issuecomment-312352650, under a discussion with zero-copy context. This has been a very old issue but I got curious after I read the recent zero-copy string/byte-buffer progress in https://github.com/protocolbuffers/protobuf/issues/1896#issuecomment-1625486127

**Comment by ericsalo** [comment]
Oh lol this is a GH thread. Now I see. Sorry, no, if this is a thing I have never heard of it myself.
