### ISSUE TITLE
 When can  support Lua?

### ISSUE THREAD

**Issue by lingfan** [google/protobuf#3312]

**Comment by xfxyjwf** [comment]
Lua is unlikely to be a first-party supported language. If you are OK with third-party implementations, there are already a few listed here:
https://github.com/google/protobuf/blob/master/docs/third_party.md

**Comment by lingfan** [comment]
no see the proto3

**Comment by watsonsong** [comment]
I am also very interesting about the official supports for lua language.
Although there has been a plenty of proto-lua thirdparty, but most of them a not up to date, and be lack of maintain. Rightnow the version of protobuf is 3.3.0, but I am still use protobuf2 because there is no suitable up-to-date lua library.
As lua is a widely useful language, especially in game design, I hope it could have official support.

**Comment by dkrikun** [comment]
Any reason lua cannot get first-class support? Lots of other languages (Ruby, Python etc.) already have.

**Comment by acozzette** [comment]
Unfortunately we just don't have the time and resources to take on official support for another language at this time.
