### ISSUE TITLE
Make `java_multiple_files` a compiler option

### ISSUE THREAD

**Issue by gcscaglia** [google/protobuf#3398]
Currently, `java_multiple_files` must be defined on `.proto` files themselves. In the [nano version](https://github.com/google/protobuf/tree/master/javanano), this option is also accepted by the compiler.

IMHO, how the classes are organized should be defined by the user of the `.proto` files, not their owner, since it doesn't affect the format on-the-wire. Is there any rationale to have the option in the `.proto` file that I'm failing to perceive? If owners are interested in a consistent class structure the can simply release jars instead of `.proto` files.

**Comment by xfxyjwf** [comment]
Take protobuf library itself as an example, it offers several google/protobuf/\*.proto for  users to use, and also provide a .jar file for users to depend on. If the user tries to override any options in any of these google/protobuf/\*.proto, the generated code simply won't compile against protobuf runtime and therefore is not usable.

As library owners, we generally don't want any configuration options that can affect the public surface of our library. That's because the more options you have, the more confusing your users will be, and very often different options interfere with each other badly. We don't want more options in the .proto files if we can, and protoc command line options are just worse. With protoc command line options, you are basically moving important information of your API out of the .proto file and hide it away from your users. If your .proto file is to be shared widely, different users using different command line options on your .proto file will prohibit code sharing and make it a disaster when someday these projects need to be fit together. In Google we take every chance to delete options from protoc, and our build tool (internal version of [bazel](https://bazel.build/)) doesn't allow custom protoc command line flags at all.

**Comment by gcscaglia** [comment]
I'm not sure if understood the first paragraph correctly. If I did, that particular problem is not protobuf specific; In any situation you provide booth the source and the output binary, it's well understood users that go for the source are doing so either because they want to modify it, or are in a platform / language for which there is no binary distributions. It's unreasonable for they to expect binary compatibility in either case, even more so if they changed the sources _or compiler options_.

As for sharing code, wasn't protobuf objective exactly _not_ sharing code, but only the _protocol_? What about situations where both ends aren't using the same language? If I understood protobuf correctly, I can have a server in java and a client in python as long as they use the same `.proto` specification. Since the python client _shouldn't_ care whether the server is using inner classes or top level ones, that info has no place in `.proto` files (Just like java package names, outer class names, etc also don't. It struck me as odd from the beginning that a supposedly language-agnostic specification format had language-specific options in source, not compiler flags).

I absolutely agree you shouldn't move important information of you API to compiler flags. But IMHO when using protobuf your API isn't the classes, it's the wire format, and classes names or organization don't (do they?) change the wire format.

**Comment by pherl** [comment]
Closing this as it's unlikely we will be able to introduce a flag this for purpose. Mostly as Feng mentioned, the symbols of the sub-message fields highly depend on the java_multiple_files option. Moving this out of the schema definition makes the symbol cross linking harder to use especially when libraries/protos are provided by different parties.
