### ISSUE TITLE
Are protobufs serialised canonically?

### ISSUE THREAD

**Issue by alamaison** [google/protobuf#3417]
I tried asking this question on the Google group but for some reason it isn't appearing:

Are protobufs serialised canonically?  By that I mean is the same message with the same fields populated with the same data guaranteed to serialise to the same sequence of bytes, regardless of language/implementation version?

The reason I ask is we're using serialised single-field protos as keys in a Kafka topic, and I'm now wondering if this is safe.  The idea was to avoid ambiguity about how to interpret the contents of the key.  However, a critical requirement of a key is that the same key must serialise to the same bytes (Kafka is only aware of bytes - nothing else).

Is what I'm doing safe?  Is it safe for some subset of proto field types (for example, I'm already pretty sure it's not safe for map types because there is no canonical ordering, right?)?

Thanks,
Alex

**Comment by xfxyjwf** [comment]
Protobuf serialization is not canonical. Do not use serialized proto as key. It's a bad practice and has been reported repeatedly as the source of problem. If you are using a single-field proto, why not just use the field's value as the key?

There are many factors making protobuf serialization not canonical. The most common one is the field ordering. There isn't a guaranteed field ordering and in particular unknown fields will be serialized in an implementation defined order. So if your proto ever changes, different version of the program will serialize the same proto differently. Addition of new features in protobuf also makes different languages serialize the same proto differently depending on whether they support the new feature or not. For example, implementations that support packed fields will serialize repeated primitive fields differently than those don't support packed fields yet. Future optimizations in protobuf may also affect the serialized bytes even if you only use the basic field types (e.g., there is a proposal to serialize varint length using 5 bytes always so we can back-fill message lengths instead of using a separate pre-calculation pass).

**Comment by alamaison** [comment]
Thanks. I suspected that might be the case.

> If you are using a single-field proto, why not just use the field's value as the key?

The aim was to allow different types of key; string, int, etc.  I think we'll just mandate string keys encoded as UTF-8 instead

**Comment by ekg** [comment]
Is a limited subset of this true? If I'm using the same C++ API generated by protoc to render the same object, should I expect field order to change?

As @xfxyjwf notes, in the wild there can be issues between implementations and with unknown fields, or with updates to the protobuf serialization model. But are these factors an issue if I wanted to use protobuf in a manner completely internal to an application, where the only reader or consumer was the particular instance of that application?

I assume I am missing something, but it would be helpful to know.

**Comment by Pique7** [comment]
Is this information still up to date? Is it possible to formulate any _"Canonical Encoding Rules"_ for Protocol Buffers meanwhile (I hope the term _"CER"_ is somewhat correct in this context)?
