### ISSUE TITLE
why this length is 4? for python

### ISSUE THREAD

**Issue by nwaycn** [google/protobuf#353]
my proto file
message get_nway_gateways_req
{
	required int32 start_pos = 1 ;  
	required int32 number_per_page = 2; 
}
and protoc to python class
then I code it:

    req_ng = gateway_op_pb2.get_nway_gateways_req()
    req_ng.start_pos = 1
    req_ng.number_per_page = 10
    s_req_ng = req_ng.SerializeToString()
    print len(s_req_nq)

the print is 4

**Comment by jake-low** [comment]
For anyone reading this in the future, the structure of @nwaycn's message when serialized is something like this:

| (5 bits + 3 bits) | 8 bits | (5 bits + 3 bits) | 8 bits |
| ------- | ------- | -------- | ------ |
| field # + wire type | varint | field # + wire type | varint |

Two things may surprise you about this:
 * field number and wire type are combined into a single byte
 * an int32 doesn't (necessarily) take up 32 bits when serialized

Both of these are intentional design decisions of the protobuf serialization format. While they might not seem intuitive at first, they allow protobufs to be very space-efficient.

For more information, check out Google's [protobuf encoding guide](https://developers.google.com/protocol-buffers/docs/encoding#varints) on the developer portal.
