### ISSUE TITLE
[feature JS] generate class names as google code standards

### ISSUE THREAD

**Issue by amelhaoui** [google/protobuf#3592]
Hi,
When using the same .proto in many languages, we have to follow coding standards for each language.
Sometimes, class names are CamelCase and in others languages snake_case
ex:
```
message hello_world {
   uint32 cool_feature = 1;
   uint32 nice_feature = 2;
}
```
Is it possible, to force the compiler to generate CamelCase classe names as it does for methods by default for JS ?

Thanks

**Comment by acozzette** [comment]
No, I'm afraid there is no way to force the compiler to generate CamelCase class names. The [style guide](https://developers.google.com/protocol-buffers/docs/style) recommends CamelCase for message names already, so ordinarily no conversion would have to happen if you go with that recommendation. I think we would be reluctant to add any protoc options for making the style configurable, because we want to avoid having extra options to maintain.

**Comment by amelhaoui** [comment]
Thanks @acozzette!
