### ISSUE TITLE
[USAGE] How do I point protoc at this ruby plugin?

### ISSUE THREAD

**Issue by ericpromislow** [google/protobuf#3609]
Not clear.  We're using `localshred/protobuf` and are considering moving to this library for generating Ruby .pb files from .proto files. What's the plugin executable I use for this library for protoc's `--plugin` option?

**Comment by acozzette** [comment]
That does look tricky, because I see that that implementation uses `ruby` as its plugin name, and we now have our own Ruby implementation that does the same. I think to use that external Ruby plugin you would want to do something like this (I have not tested this, though):
`protoc --myruby_out --plugin=myruby=/full/path/to/plugin ...`
By giving it the name `myruby` that should avoid a conflict our internal Ruby implementation.

**Comment by ericpromislow** [comment]
Thanks @acozzette. My dumb question is what's the path to the plugin that a successful run of `rake` produces?

**Comment by acozzette** [comment]
Wouldn't this plugin be the one at `bin/protoc-gen-ruby` [here](https://github.com/ruby-protobuf/protobuf/blob/master/bin/protoc-gen-ruby)? Though I admit I'm not very knowledgeable about Ruby and so I am not sure.

**Comment by ericpromislow** [comment]
ok, I get it now. We're using a plugin to generate v2-compatible code.
Running without a plugin will generate v3-compatible code, which we're not
ready for. Thanks.

**Comment by acozzette** [comment]
Ah yes, I believe our Ruby implementation is proto3-only, so if you need proto2 then that makes sense to stick with that third-party implementation.
