### ISSUE TITLE
Java Enum Generation

### ISSUE THREAD

**Issue by wscheffer** [google/protobuf#3640]
So I was wondering in the Java Enum Compiler why is there an `UNRECOGNIZED` value if `default` for the `forNumber` returns `null` would it not make more sense to `return UNRECOGNIZED`?

https://github.com/google/protobuf/blob/80a37e0782d2d702d52234b62dd4b9ec74fd2c95/src/google/protobuf/compiler/java/java_enum.cc
Line 202

**Comment by BSBandme** [comment]
@xfxyjwf  java enum behavior question

**Comment by xfxyjwf** [comment]
`forNumber` replaces `valueOf` and since `valueOf` returns `null` on unknown value so must `forNumber`. The `UNRECOGNIZED` value is only generated for proto3 and was introduced after `valueOf`/`forNumber` exists, so it can't really be used there. We also can't make the change now because it's an API breaking change.
