### ISSUE TITLE
Add proto generation for C# under Windows

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#375]
Pull request #373 added shell scripts to generate proto files under Unix; we should have the same ability for Windows when protoc.exe has already been built. Ideally this would be an msbuild target, but it could also be a batch script for the moment.

**Comment by jtattermusch** [comment]
I am almost leaning towards not creating a batch script for windows, so that we have a just a single file for regenerating proto and thus maintain its single source of truth status. Keeping two scripts that do the same thing in sync seem like a pain.
As you said, it would be good if we could come up with a nice portable way (perhaps msbuild/xbuild based) to regenerate the protos.

**Comment by jskeet** [comment]
Well, without *any* way of regenerating the files on Windows, that basically makes it infeasible to develop the runtime in Windows - which would be pretty odd when that's the primary platform for most C# developers. An msbuild solution is definitely the ideal; will investigate it further. (We already have some code to do it, but it's out of date.)

**Comment by jskeet** [comment]
I've started looking into msbuild, but it'll take quite a while to get my head round how to do it properly.
In the meantime, I've added a pull request to make generate_protos.sh find a suitable protoc file, probing vsprojects/Debug/protoc.exe, vsprojects/Release/protoc.exe, and src/protoc.

This should be a short term fix allowing development under Windows for anyone who has a Bash shell installed - which happens by default when you install msysgit...

**Comment by jskeet** [comment]
Superceded by #1193.
