### ISSUE TITLE
C++ API generated by protoc partially broken?

### ISSUE THREAD

**Issue by HarHarVeryFunny** [google/protobuf#3810]
The C++ API generated by protoc (latest release 3.4.1) for repeated message fields seems partially broken.

Given definitions:

message Foo {
  optional string name = 1;
}

message Bar {
  repeated Foo foo = 1;
}

The API provides two alternates for iterating over repeated embedded message fields:

1) Index-based : OK

const Foo& Bar::foo(int index) const; // const method returns const reference

Foo* Bar::mutable_foo(int index); // non-const method returns non-const pointer for mutability

2) "STL-like iterator"-based : seems broken

RepeatedPtrField< Foo >& Bar::foo() const;

RepeatedPtrField< Foo >* Bar::mutable_foo();

This second STL-like API has the following issues:

a) foo(), unlike foo(int), behaves as a collection of non-const Foo despite being a const interface

b) mutable_foo() behaves as a collection of Foo rather than Foo*, and therefore fails to provide a mutable interface
		 
c) mutable_foo() oddly returns a pointer to collection rather than a collection itself

These issues manifest as follows:

for (auto foo : bar.foo()) {
  foo.set_name("fred"); // wrongly allowed, since non-const, but ineffectual anyway since value vs reference
}

for (auto foo : *bar.mutable_foo()) { // need to dereference collection !
  foo.set_name("fred"); // ineffectual since value vs expected pointer as returned by mutable_foo(int)
}

It seems the STL-like API should really be:

RepeatedPtrField< const Foo & > Bar::foo() const;

RepeatedPtrField< Foo * > Bar::mutable_foo();

Which would then support:

for (auto foo : bar.foo()) {
  foo.set_name("fred"); // compilation error - attempt to modify const object
}

for (auto foo_ptr : bar.mutable_foo()) {
  foo_ptr->set_name("fred"); // successfully modified via pointer - mutability achieved!
}

**Comment by acozzette** [comment]
@HarHarVeryFunny Those are some fair criticisms of the repeated field API. The way it currently works is that it basically exposes the internal object used to store the repeated field, whereas ideally we would want to expose a more user-friendly view of that. It sounds like you are envisioning that `RepeatedPtrField` would be more like a view that points to the data rather than actually owning the data.

We tend to be reluctant to make any breaking API changes unless there is a highly compelling reason, so unfortunately we will probably have to live with the current API for now, unless you have ideas on how to change it in a way that remains backward-compatible for existing users of the code.

**Comment by xfxyjwf** [comment]
The current API is working as intended:

1. The signature of the const accesser is `const RepeatedPtrField<Foo>& foo() const;`. I don't know why you see a non-const reference as return type, but if you have a case to reproduce it, that's a bug we need to fix.
2. `RepeatedPtrField<Foo>` functions exactly like a standard container type and you should use it like a standard container type (think of it as `vector<Foo>`). For example, if you want to get a mutable reference to elements in a `vector<Foo>`, you should do:
    ```cpp
    vector<Foo> foos = ...;
    for (auto& foo : foos) {
      foo.set_name(...);  // This will modify the object in the container.
    }
    ```

    Likewise, with proto API, it's:

    ```cpp
    for (auto& foo : *bar.mutable_foo()) {
      foo.set_name(...);  // This will modify the Foo object in the container.
    }
    ```

I think the problem you are having are mostly caused by the misuse/misunderstanding of the C++ `auto` keyword. If you want a reference, you need to write `auto&`.
