### ISSUE TITLE
com.google.protobuf:protobuf-lite hasn't been published to maven central recently

### ISSUE THREAD

**Issue by okorz001** [google/protobuf#3821]
The most recent release of protobuf-lite on maven central is 3.0.1 from 2016-07-28:
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protobuf-lite%22

This is mildly annoying since grpc-protobuf depends on both protobuf-java and protobuf-lite and I am trying to force same versions across com.google.protobuf (and io.grpc) in gradle. This also raises concern about whether protoc and protobuf-java are guaranteed backwards compatible with older releases of protobuf-lite.
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protoc%22
http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.protobuf%22%20AND%20a%3A%22protobuf-java%22

**Comment by xfxyjwf** [comment]
protobuf-java-lite will not have the same version number as protobuf-java/protoc. Instead, protoc-gen-javalite/protobuf-java-lite will be versioned together and independently from protoc/protobuf-java. When using lite, make sure:

1. You have the same version number for protoc-gen-javalite and protobuf-java-lite.
2. The version of protoc doesn't matter for lite and any version should work.
3. Never use protobuf-java with lite because they are incompatible.

**Comment by okorz001** [comment]
Thanks for clarifying.

On further inspection of the grpc-protobuf pom, I see that although it depends on grpc-protobuf-lite, protobuf-lite is supposed to be excluded. I am not sure why that is not being honored in gradle, but I will add an explicit exclusion in our build.
http://search.maven.org/#artifactdetails%7Cio.grpc%7Cgrpc-protobuf%7C1.4.0%7Cjar
