### ISSUE TITLE
[JS] proto.google.protobuf.StringValue does not work correctly.

### ISSUE THREAD

**Issue by neurojab** [google/protobuf#3823]
If you set a value using StringValue, then call getValue() you will only get the first character.  

Example test:

it(‘should Serialize and deserialize correctly’,
        function() {
            let mystr = ‘AAAD12324’;
            let protoValue = new pport.wrappers_pb.StringValue(mystr);
            let mystrFromProto = protoValue.getValue();
            console.log(mystrFromProto);
            assert(mystr === mystrFromProto);
        });

Console.log Output:  
A

**Comment by neurojab** [comment]
Also, including the StringValue in a message and serializing to binary seems to serialize it as an array of one character

**Comment by neurojab** [comment]
I'm unblocked if I use the empty constructor for StringValue and then call setValue.   

Still, shouldn't the constructor work correctly if at all?

**Comment by nvartolomei** [comment]
This is because StringValue is a message, and it's constructor accepts an array representation of created message and not the string itself.

The right way to build StringValue message is to create it, and then to invoke `setValue`.

Of course, because you know it's internals you also can use `new StringValue([mystr]);`, it will put first array element inside first message field.

**Comment by haberman** [comment]
@nvartolomei is correct here, StringValue is a message with a single field. You have to set its value manually, there is no special support for this.
