### ISSUE TITLE
java-lite generated classes don't work with 3.5.0

### ISSUE THREAD

**Issue by fifteenhex** [google/protobuf#3879]
GeneratedMessageLite in 3.5.0 tries to invoke "GET_MEMOIZED_IS_INITIALIZED" in generated classes but the latest generator for java-lite (3.0.0) doesn't generate code to handle that so an UnsupportedOperationException is thrown.

**Comment by pherl** [comment]
java-lite has its own branch "javalite" and hasn't been released for a while. The 3.0.0 plugin in javalite branch won't work with 3.5.0 java runtime in master branch. Please refer to the [maven central repo](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.google.protobuf%22) for the matching protobuf-lite and protoc-gen-javalite

**Comment by sirthias** [comment]
Just like the previous version protoc 3.5.0 happily compiles `.proto` files with `option optimize_for = LITE_RUNTIME;`.

However, now that blow up at runtime with an `java.lang.UnsupportedOperationException`.

Whatever the reason is, I would definitely consider this behavior a bug, since either `optimize_for = LITE_RUNTIME` is supported or it isn't. If it is supported it should work properly (as it did in 3.4.0) or, if it isn't supported, the compiler should bark about it *at compile* time, rather than produce broken code.

Therefore I'm surprised to simply see this ticket being closed.

**Comment by pherl** [comment]
optimize_for = LITE_RUNTIME works if you have a matching protobuf-lite
runtime (not the 3.0.0 runtime). The error was triggered by the mismatched
generated code and runtime which we are not able to detect at compile time.
It's unfortunate that 3.0.0 runtime works with 3.4.0 generated code - it is
completely untested. I would use the 3.0.0 compiler instead even if it
seems to work. In the future, we will always throw runtime exceptions for
such version mismatch.

**Comment by fifteenhex** [comment]
I think the reason we're using the 3.4.0 runtime because the 3.0.0 lite version didn't have some standard .proto files included and some other library we're using is pulling in 3.4.0 too.
