### ISSUE TITLE
Issues identified in version 3.4.0 by security scan

### ISSUE THREAD

**Issue by smbmobile63017** [google/protobuf#3893]
Tho following 3 issues were flagged by a security scan where we use Protobuf v3.4.0. Will these be resolved in an upcoming version?
 
1. Unchecked CString Convertion
The element Param at line 273 of /Protobuf/objectivec/GPBCodedOutputStream.m contains a C-String that was converted from a CFString object. The length of Param was not checked after conversion.
Method: (void) writeStringNoTag:(const NSString *) value 
Line: 294
**result = [value getBytes:state_.bytes + state_.position** 
 
2. Unchecked CString Convertion
The element CFStringGetCStringPtr at line 273 of /Protobuf/objectivec/GPBCodedOutputStream.m contains a C-String that was converted from a CFString object. The length of CFStringGetCStringPtr was not checked after conversion.
Method: (void) writeStringNoTag:(const NSString *) value 
Line: 281
**CFStringGetCStringPtr((CFStringRef)value, kCFStringEncodingUTF8);** 
 
3. Improper Resource Shutdown or Release
The application's - method in /Pods/Protobuf/objectivec/GPBCodedOutputStream.m defines and initializes the output object at 173. This object encapsulates a limited computing resource, such as open file streams, database connections, or network streams. This resource is not properly closed and released in all situations.
Method: (instancetype)initWithOutputStream:(NSOutputStream *)output 
Line: 177
**[output open];**

**Comment by thomasvl** [comment]
First up, what tool is this and is there a way we can run this?  I'm wondering if there is some more info in a UI or something that would help use directly to see if there is more info provided to help understand these better?

For 1 - We aren't really sure what the issue is talking about here.  I believe the _C-String_ reference could be to the `quickString` variable in that code, but line 294 doesn't use the variable.  So it isn't really clear what it is saying is an issue.  Was there anything more in the report to help understand it?

For 2 - Again we aren't completely sure what this one is trying to say.  Line 281 does extract the C-String, but where `quickString` is used (lines 290 and 310), we use `length` which was directly collected from the original `NSString` (`value`) with a UTF-8 conversion matching out the C-String was collected.  I guess in theory could could be a mismatch, but at that point you are worrying about about some pretty fundamental bugs in Foundation, and I'm not sure one could be defensive against apis returning wrong values.  Anyway, more info for specifically what it is raising as an issue would help confirm if it is these two later lines or something else.

For 3 - Our guess here is the tools doesn't like the fact that the `-open` was done with the `output` parameter, but the `-close` in `-dealloc` is done with `_state.output` (because it does't realize the assignment into `_state.output` is tracking the same resource.  I've done #3916 to tweak the code so maybe the tool will see that better, but the existing code always did close the stream.

**Comment by anandolee** [comment]
We are closing it for cleaning. Feel free to reopen it if it is still an issue
