### ISSUE TITLE
v3.5.0 vs v3.4.0 Python Decimal Parsing

### ISSUE THREAD

**Issue by trueromio** [google/protobuf#3913]
Hi,
when I update protobuf from 3.4.0 to 3.5.0, I receive next error:
```
_env/lib/python3.6/site-packages/protobuf-3.5.0-py3.6.egg/google/protobuf/internal/python_message.py:662: in field_setter
    new_value = type_checker.CheckValue(new_value)

self = <google.protobuf.internal.type_checkers.TypeCheckerWithDefault object at 0x7f44dfec2c50>, proposed_value = Decimal('6.42000')

    def CheckValue(self, proposed_value):
      """Type check the provided value and return it.
    
        The returned value might have been normalized to another type.
        """
      if not isinstance(proposed_value, self._acceptable_types):
        message = ('%.1024r has type %s, but expected one of: %s' %
                   (proposed_value, type(proposed_value), self._acceptable_types))
>       raise TypeError(message)
E       TypeError: Decimal('6.42000') has type <class 'decimal.Decimal'>, but expected one of: ((<class 'numbers.Real'>,),)

_env/lib/python3.6/site-packages/protobuf-3.5.0-py3.6.egg/google/protobuf/internal/type_checkers.py:109: TypeError
```
Is it expected behavior? Looks like a bug.

**Comment by anandolee** [comment]
We changed the type check to accept numbers.Real (it was int, long, float in 3.4.0). However, the original 3.4.0 should also reject 'decimal.Decimal'. Can you double check if it can pass on 3.4.0.

Can you also provide more detail of your code

**Comment by trueromio** [comment]
Sorry, my bad. Just doublechecked and found the same behaviour in 3.4.0
In my client code, I've added the conversion from Decimal to float to mitigate this.

**Comment by PeterJCLaw** [comment]
I realise this is an old and closed issue, but I've just hit something similar while upgrading from Python 3.9 to 3.10. I was using protobuf 3.15.8, which has wheels for 3.9 but not 3.10.
The difference for me seemed to be that on 3.10, which appeared to use the pure-Python implementation I got the error whereas on Python 3.9 my input `decimal.Decimal` was converted to a `float`.

Having upgraded to protobuf 3.19.4 (which has wheels for Python 3.10) the difference has gone away.
On both Python 3.9 and 3.10 `decimal.Decimal` is not considered a `numbers.Real`, so that's unlikely to be responsible for the difference.

This would appear to suggest there's a difference between the native implementation and the pure-Python implementation.

I note however that following https://github.com/protocolbuffers/protobuf/commit/3ab97ce8301183b46a4412b28171512f00f8edb9 the implementation of the pure-Python version has changed substantially so it's possible that the difference is now gone too (certainly it looks to me like the new implementation would allow `Decimal`s).

Hope this helps anyone else who hits this.
