### ISSUE TITLE
Avoid C++11 warning for switch on proto3 enum w/o a default clause

### ISSUE THREAD

**Issue by chhsia0** [google/protobuf#3917]
Hi all,

I'm from the Apache Mesos community and I've asked a related question here:
https://groups.google.com/d/msg/protobuf/YefxUmgxvg4/1P7QZHstBAAJ
We usually don't use a `default` clause when doing a `switch` statement on a proto enum, so the compiler can detect errors when one adds a new enum value in a proto definition but forgets to add the corresponding `case` clauses. This works well for proto2 enums, and ideally it would be nice if the following code works in proto3:
```
message Foo {
  enum Type {
    FOO = 0;
    BAR = 1;
  }
  Type type = 1;
}
```
```
int HandleFoo(Foo foo) {
  if (Foo::Type_IsValid(foo.type()) {
    switch (foo.type()) {
      case FOO: return ...;
      case BAR: return ...;
    }
  } else {
    // Handle the unknown enum value properly.
  }
}
```
If someone adds a new `BAZ` enum into `Foo.Type`, then we'd like the compiler to generate a warning to tell us that the `switch` statement is incomplete, and with the `-Werror` flag turned on, the compiler will prevent the above code from compiling. On the other hand, if the protobuf at the receiver-end is not updated, the `if` statement can prevent the code from receiving an unrecognized enum value.

Unfortunately, the above code doesn't compile with `-Werror` on due to the `*_SENTINEL_DO_NOT_USE` values introduced in proto3 open enum, and there is no way to ask the compiler to only report error on missing non-sentinel enum values in `switch` statements.

It seems to me that there are some merits to consider removing or standardizing the sentinel enum values to allow such compiler checks. Thoughts?

**Comment by xfxyjwf** [comment]
@pherl

**Comment by pherl** [comment]
One workaround is to add the default case, then static_check the size of the enum.

**Comment by yzhao1012** [comment]
Sorry for reviving an old thread.

@liujisi 
> static_check the size of the enum

What does this mean?

**Comment by acozzette** [comment]
I think the idea is that you could use a `static_assert` as an alternative way of causing the compiler to error out when a new enum value is added. For an enum called `MyEnum`, protoc will generate a constant `MyEnum_MAX` which you could assert on.

**Comment by ppanhoto78** [comment]
Just curious to what would be the point of these sentinels.
They are defined as:

```
  Enum_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Enum_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
```
Any interested party could retrieve these values at compile time with `std::numeric_limits<std::underlying_type_t<EnumType>>` like the example below:
```
#include <limits>
#include <type_traits>
#include <iostream>

enum X: int {
    A,
    B,
    C
};

int main() {
    using limits = std::numeric_limits< std::underlying_type_t< X > >;
    std::cout << limits::min() << '-' << limits::max() << '\n';
}
```

**Comment by acozzette** [comment]
They are meant to prevent anyone from writing a `switch` statement without a `default` case. (I think in the past they might have also served the purpose of ensuring the enum is large enough to store an `int`, but that is no longer necessary since we now specify `enum X: int`.)

The `default` case is very important because there is no guarantee that the value will be one of the explicitly named enum values. For a proto3 message, when you call an enum getter you will get whatever value was parsed from the wire. If you're reading a message that was serialized by a newer binary then there may very well be a value that the parsing binary does not know about yet. I often see buggy code that tries to do things like this:
```
int MyFunc(const MyProto& m) {
  switch (m.some_enum()) {
    case A: return 5;
    case B: return 7;
    case SomeEnum_INT_MAX_SENTINEL_DO_NOT_USE_: return 0;
    case SomeEnum_INT_MIN_SENTINEL_DO_NOT_USE_: return 0;
    // No default case! If there is an unexpected value then this function will fall
    // through to the end without returning anything. This is undefined behavior.
  }
}
```
Proto2 messages handle this differently and store any unknown enum values in the unknown field set, so with proto2 you could omit the `default` case without running into the problem above. But the proto2 behavior is a serious design flaw because many things can go wrong when unknown enum values are silently hidden in the unknown fields unexpectedly.
