### ISSUE TITLE
Repeated value in maps

### ISSUE THREAD

**Issue by mavle** [google/protobuf#3992]
Hello, I would like to propose supporting the repeated type in map values. With projects like grpc-gateway protobufs are increasingly being converted to JSON. Often the user touchpoint is with the JSON object itself. There are many good reasons for a map of list.
```
{
  "/myroute": [
      {
        "action": "GET",
        "params": "myparms"
      },
      {
        "action": "POST",
        "params": "otherparms"
      }
  ],
  "/newroute": [
      {
        "action": "PUT",
        "params": "myparms"
      }
  ]
}
```
this in proto becomes:
```proto
message Routes {
    map<string, RouteAttrArr> attr = 1;
}

message RouteAttrArr {
    repeated RouteAttr routeattr = 1;
}

message RouteAttr {
    string action = 1;
    string params = 2;
}
```
This is convoluted and in turn yields redundant JSON, for what should be a simple relationship type. For protobuf to be more widely adopted it should have direct parity with available JSON relationships.

**Comment by acozzette** [comment]
I am afraid we will probably not be able to do this. Unfortunately the thing with this kind of change is that it ends up being a huge amount of work because it has to be repeated for every language we support, so there has to be an extremely high bar for the benefits it would bring. But another approach to consider would be to focus on the JSON format alone. For example, maybe `RouteAttrArr` could have an annotation on it to indicate that it should just show up as a list in JSON.

**Comment by mavle** [comment]
Solving it on the generation end is possible but not desirable for a lot of the same reasons as on your end. The need to now do that to all of the languages generated would be immense. 

Is there a place to make considerations for protobuf v4.0? Or would the same restrictions entail? This looks like a legitimate improvement if it could be fit in at the right time.

**Comment by acozzette** [comment]
We haven't even really started thinking about 4.0 yet, but I think this would be a tough sell even when we do a new major version.
