### ISSUE TITLE
Is protobuf safe to handle untrusted data (csharp) ?

### ISSUE THREAD

**Issue by PencilBow** [google/protobuf#4009]
Hi,

I'd like use this library to accept messages from untrusted (Unity) clients. The clients might try and tinker with the binaries to (DDOS) attack our servers. (Server also in Unity).

Is there no way a attacker could send a message that:

- take unproportial cpu to decode
- take unproportial memory to decode
- instantiate a random C# class / call unwanted methods.

If the answer is no:
Are there any options in order to prevent these attacks?

**Comment by jskeet** [comment]
The only thing I can think of offhand is that map fields don't have any hash randomization. If an attacker provided a map field with keys that had the same hash but weren't equal, I suspect that would cause O(N^2) computation. We don't currently have any options that would mitigate that other than not using map fields.

**Comment by PencilBow** [comment]
@jskeet Thanks for the answer. O(N^2) would still be acceptable to us, if that is the worst case.

Just to absolutely sure I'm communication my intent correctly, there is no amount of header-tinkering that can cause the machine to allocate an arbitrary amount of memory unnescessarily?
(I am being overly careful because I have observed exactly this is in a few libraries already)

**Comment by jskeet** [comment]
Not overly-persistent at all... I was very foolish (and shouldn't answer questions at the end of the day). A claim of a huge *message* isn't too bad (as far as I can remember; I'd have to check line by line for details, but I believe it just sets how much data we read from the stream) - but *strings and bytes* allow arbitrary allocation.

I don't know of any mitigation of that at the moment. It wouldn't be impossible to add a per-string/bytes limit when reading, although that would obviously limit what legitimate data would be representable.

**Comment by PencilBow** [comment]
Thanks for the confirmation. Although I would be interested in these safeguards, a solution is needed sooner than later. 
I think I will go with JSON (sigh) as it's the only format I've found that does not allow arbitrary allocation.

**Comment by PencilBow** [comment]
@jskeet out of curiosity I read through some of protobuff's source-code. It seems like there *are* safeguards in place! Is there something I'm missing that does allow for arbitrary allocation?
```
// The size is very large.  For security reasons, we can't allocate the
// entire byte array yet.
```
[https://github.com/google/protobuf/blob/426cf6f31ed5efae703d7a1f31edc841205414e2/csharp/src/Google.Protobuf/CodedInputStream.cs#L1139](url)

**Comment by jskeet** [comment]
Gosh - I don't remember putting that in place! That does look appropriate, and ReadString goes through the same path.

Maybe that's enough - but I'm not going to guarantee that there aren't other aspects that could allocate arrays without taking that much care, e.g. for a packed repeated field. Knowing that one attack vector is shut off isn't enough to be safe, of course. Repeated field handling looks okay based on this:

https://github.com/google/protobuf/blob/master/csharp/src/Google.Protobuf/Collections/RepeatedField.cs#L96

... but that was just *one* thing I thought of.

I'm afraid I don't have the time - or the skill, to be honest - to look over the code and consider *every* attack vector (as there may be some I'm unaware of). It's possible that someone on the protobuf team has more experience of this than I do.

**Comment by xfxyjwf** [comment]
I think we can check the parsing code for every field type that uses LENGTH_DELIMITED wire format because that's the only wire type where pre-allocating large chunk of memory can possibly happen. Among those:
1. message field type should be safe because we only allocate the message object itself and can't allocate more memory for its fields without actually parsing the content.
2. string/bytes field type needs to be checked and they seem safe given the implementation in CodedInputStream.
3. Packed fixed-width ints. The code in RepeatedField seems safe to me.

Other than those I can't think of any other place that can pre-allocate large chunk of memory based on input data.

Another thing you might want to check is stack-overflow due to deeply recursive message structure and such safeguard also exists in C# already:
https://github.com/google/protobuf/blob/426cf6f31ed5efae703d7a1f31edc841205414e2/csharp/src/Google.Protobuf/CodedInputStream.cs#L572

It seems to me except for map hash-flooding all other protections implemented in C++/Java are also in place in C#.
