### ISSUE TITLE
Windows ARM64 support

### ISSUE THREAD

**Issue by mkamilov** [google/protobuf#4048]
Protobuf build fails to build in Windows ARM64 platform.

Adding following lines into platform_macros.h can solve the problem.

```
defined (_M_ARM64)
#define GOOGLE_PROTOBUF_ARCH_ARM 1
#define GOOGLE_PROTOBUF_ARCH_64_BIT 1
```

**Comment by acozzette** [comment]
@mkamilov Could you send us a pull request?

**Comment by lordspecter13** [comment]
hello, never ask for any changes to my accounts right now and damaged my computers, but do not worry all the information is already stored and google official is aware of their illegal acts, github is also complicated because it does nothing to reverse the acts , this machine is a zte blade v6 plus version 6.0 and it does not appear because the reason for the illegal change was so that I could not ask google developers for help and my datas were not read, but I found the way
