### ISSUE TITLE
Is there a way to generate POD data types for C++?

### ISSUE THREAD

**Issue by Zeks** [google/protobuf#4078]
We've been converting protbuf generated classes to and from pure c++ PODs in our application for some time now, could it somehow be automated? Like some plugin that generates POD classes and conversion functions between full and POD classes? We really don't want or need to pass protobuf headers throughout whole application logic.

**Comment by acozzette** [comment]
Do you mean POD types as defined by the C++ standard, or more like simple structs that contain the data but no serialization code? I think POD types as defined by the standard would be tough to work with since they cannot have user-defined destructors.

I think it would be doable to generate structs and conversion code if you want to do that. You can pass the `--descriptor_set_out` option to `protoc` to have it write out the descriptors to a file, and then you can have a simple program read in the descriptors and generate the code from them. This could be part of the build so that it happens automatically.

Are you sure you want to do this, though? I suspect there would be a performance penalty to doing these conversions, and then just the added complexity of having an extra type for each message. Have you thought about using forward declarations or some other kind of encapsulation to limit protobuf headers from being pulled into too many files in your codebase?
