### ISSUE TITLE
The format is wrong when output int_64 to JSON..

### ISSUE THREAD

**Issue by imkcy9** [google/protobuf#4103]
When I use MessageToJson function serializing "int64  n" to JSON, the value of n is 40, it should output like {"n":40 },   but the fact is output like {"n":"40"}, how to fix it ??

**Comment by trianta2** [comment]
I believe [this is the line](https://github.com/google/protobuf/blob/master/python/google/protobuf/json_format.py#L267) that causes the unexpected output.

This may be a bandaid fix due to a limitation in JavaScript, i.e. it doesn't have support for 64 bit integers, only doubles. Perhaps preserving the original value as a string allows the module to decode it correctly.

**Comment by xfxyjwf** [comment]
JSON implementations may not support 64-bit integers so to guarantee the value can be round-tripped we print 64-bit integers as strings. If you are consuming the proto JSON output directly, make sure you are doing it in accordance with the proto3 JSON mapping here:

https://developers.google.com/protocol-buffers/docs/proto3#json

Specifically you should accept both numbers and strings for 64-bit proto fields.
