### ISSUE TITLE
Unresolved external fixed_address_empty_string when trying to use dll on windows MSVC 2015

### ISSUE THREAD

**Issue by jpwhiting** [google/protobuf#4118]
As has happened before (and somehow still happens even if I use the commits right after the fix is merged) if I build dll on windows with MSVC 2015 and try to link to libprotobuf I get an unresolved external symbol class google::protobuf::internal::ExpliticlyConstructed<class std::basic_string<char, struct std::char_traits<char>, class std::allocatar<char> > > google::protobuf::internal::fixed_address_empty_string

Checking the dll with dumpbin /exports shows fixed_address_empty_string was exported, yet linking fails to see it somehow...

**Comment by pim89** [comment]
May be related to [this commit](https://github.com/google/protobuf/commit/9094bf0f7e638f68cae72581ae8416e7c2721b41). For some reason this commit has been reverted at some point.

**Comment by jpwhiting** [comment]
Yeah, that's what I mean. I've put that back in locally and still have unresolved external when linking against libprotobuf or libprotobuf-lite. More investigation shows the symbol is in libprotobuf-lite only since libprotobuf doesn't include generated_message_utils.cc while libprotobuf-lite does. Either way trying to link to either libprotobuf.dll or libprotobuf-lite.dll gives me the same unresolved external. Using dumpbin /exports on the .lib or .dll generated shows the symbol is there, but maybe it's there as an export but not defined or something? My MSVC c++ knowledge has hit it's limit trying to figure out the cause or a solution to this issue.

**Comment by pim89** [comment]
hm strange. For me this was the reason to switch to a static library.
If you've generated the project with the protobuf_BUILD_SHARED_LIBS flag enabled in cmake and used #define PROTOBUF_USE_DLLS at the top of your program it should work. I'm not too knowledgeable about this either though.

**Comment by jpwhiting** [comment]
I added #define PROTOBUF_USE_DLLS to the top of my source file, do I also need to add it to the .cc file that protoc generates for me?

I initially tried using static lib but got a conflict because I'm also using Qt dlls so msvc complained that I couldn't use both static and dynamic linking somehow...

**Comment by pim89** [comment]
You could try adding it as a preprocessor define as suggested [here](https://github.com/google/shaka-packager/tree/master/packager/third_party/protobuf/vsprojects). I guess this is what is done [here](https://github.com/google/protobuf/issues/3994) though i dont know wat 'blurb' means...

I dont know what kind of error you get when using a static build, but for it works when I build protobuf as a static library but with the dynamic run-time library, so with build option /MD instead of /MT.

**Comment by jpwhiting** [comment]
Ah, I'll give that a try, thanks, I got it to work as a dll just now though, by editing the generated .cc files to add PROTOBUF_USE_DLLS to the top. I would rather statically link, I'll try that, thanks for the tips.

**Comment by jpwhiting** [comment]
yep, specifying -Dprotobuf_MSVC_STATIC_RUNTIME=OFF fixed the issue I saw before from the default of having static runtime linked. Thanks again.

**Comment by jgreen-zynga** [comment]
This thread came up for me while I was googling issues to my own problems, I fixed _my_ issue with this:

Ran into something that looked similar to compiling a compiling static libprotobuf.lib on windows for integration with a C++ 20 project. Turns out the difference was in c++ version processing the header port.h differently.

```
commit 0d815c5b74281f081c1ee4b431a4d5bbb1615c97 (HEAD, tag: v6.30.1, tag: v4.30.1, tag: v30.1)

unresolved external symbol "class google::protobuf::internal::GlobalEmptyString const google::protobuf::internal::fixed_address_empty_string" (?fixed_address_empty_string@internal@protobuf@google@@3VGlobalEmptyString@123@B)

dumpbin /exports /symbols libprotobuf.lib
00F 00000000 SECT5  notype       External     | ?fixed_address_empty_string@internal@protobuf@google@@3VGlobalEmptyString@123@A (class google::protobuf::internal::GlobalEmptyString google::protobuf::internal::fixed_address_empty_string)


Note the constness is different (`@A` vs `@B`) 

// port.h
#if defined(__cpp_lib_constexpr_string) && __cpp_lib_constexpr_string >= 201907L
```

My solution was to set `-DCMAKE_CXX_STANDARD=20` and do a -clean-first build of libprotobuf, but presumably downgrading the target project would have also worked.


Tangential to the external symbol, I also ran into MSVC_STATIC_RUNTIME issues and had to set both protobuf and absl to off `-Dprotobuf_MSVC_STATIC_RUNTIME=OFF -DABSL_MSVC_STATIC_RUNTIME=OFF` to match the target project's settings.

**Comment by Alouettesu** [comment]
When I built protobuf 30.0.0 with MSVC, I've met same error. I found definition of `fixed_address_empty_string` in src/google/protobuf/port.cc:

```lang-cpp
#if defined(__cpp_lib_constexpr_string) && __cpp_lib_constexpr_string >= 201907L
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT const GlobalEmptyString
    fixed_address_empty_string{};
#else
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GlobalEmptyString
        fixed_address_empty_string{};
#endif
```

This symbol hadn't been included into object file while using C++17. I 've enabled C++20 and it's ok.
