### ISSUE TITLE
Factory methods for non-wrapper types in Java

### ISSUE THREAD

**Issue by dmdashenkov** [google/protobuf#4258]
Protobuf generated code in Java enables a convenient feature for the primitive wrapper types — the message has the `of(<primitive type>)` static method.

According to the [codebase](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/java/java_message.cc#L544), the methods are generated only for the [wrapper types](https://github.com/google/protobuf/blob/07b9238a1c03ef0351bcb4ca57d773eb7b7c5824/src/google/protobuf/compiler/java/java_helpers.h#L381), at least as far as I can see.

My question is: is there another way to generate this kind of method for all the single-field types?
If not, may we expect to see this feature in future?

Also, I'm aware of the possibility to create custom `protoc` plugins and generate factory methods "manually". Though, this seems a bit too complicated for such purpose.

**Comment by xfxyjwf** [comment]
Generating the 'of' method is only possible if the proto is guaranteed to only ever has one single field. I doubt we will add it for users' protos because we just don't have the same level of guarantee.

You can though propose new proto types into the protobuf library. If it's added to protobuf library, we are not limited to the 'of' method but can actually provide more specialized helpers appropriate for the type (e.g., google.protobuf.Any has pack() and unpack() methods).

**Comment by dmdashenkov** [comment]
Thank you for making it clear, @xfxyjwf.
