### ISSUE TITLE
C++11 features

### ISSUE THREAD

**Issue by Sagar19shah** [google/protobuf#4352]
Hello,

I want to use move semantics for the getter methods. Is that supported? I see all getter methods return const &. I want to move some of the variables like string . Any plans for adding this feature?

**Comment by pherl** [comment]
The object returned by the getter is still owned by the parent message.  They are not rvalue and cannot be moved. Otherwise the parent message would end up in a corrupted state.

**Comment by Sagar19shah** [comment]
Thanks for the response. 

I understand what you have mentioned is the current implementation which does not support move. However with support for move available in C++ we should make use of it. And it's pretty basic and widely use case we will be supporting - apps receiving data would be able to use move instead of copying the data in their own data structures.

**Comment by pherl** [comment]
But the getter returned objects are not temp objects. There is no copy happening when you call the get - it returns the address pointing to the original data, which you cannot and should not modify. 

If you need to consume the input message and move the fields in it to another message, you can explicitly call release_foo() to transfer the ownership of the sub message fields to the new message.

**Comment by arthur-tacca** [comment]
I think there is some confusion here about whether you really want to move from a field in your source message, which would modify it. Just to be clear here, imagine this bit of pseudo-code:

    // This is just pseudo-code
    dest_msg.my_str_field = src_msg.my_str_field

Obviously, this should change the value in `dest_msg.my_str_field`. But what do you want to happen to the value in `src_msg.my_str_field`?

1. `src_msg.my_str_field` should be unchanged i.e. retain its original value.
    * In that case it is absolutely necessary to do a copy of the underlying string.
    * That looks like this: `dest_msg.set_my_str_field(src_msg.my_str_field())`
    * As @pherl already said, the current implementation only does one copy, which is the best that can be done:
    * `my_str_field()` does zero copies because it returns a reference to the underlying string.
    * `set_my_str_field()` with a `const std::string&` does a single copy.
2. You don't care about the new value of `src_msg.my_str_field` i.e. it can be changed to anything.
    * If this really is what you want, this is already possible: use the `mutable_*()` accessors.
    * It looks like this: `dest_msg.set_my_str_field(std::move(*src_msg.mutable_str_field()))`
    * `mutable_my_str_field()` returns a `std::string*` which you can dereference and move from.
    * `set_my_str_field()` has an overload that takes a `std::string&&`.
3. `src_msg.my_str_field` should become empty.
    * In this case, you can do a move as suggested in 2, but then you need to clear the source string.
    * The second line looks like this: `src_msg.clear_my_str_field()`.
    * I mention this because a common mistake is to believe that objects should be empty after you move from them, when in fact they are allowed to have *any* value unless explicitly documented.

To reiterate, you can move from a field already but it will change the source value (of course), and it looks like this:

    destination_msg.set_my_str_field(std::move(*source_msg.mutable_my_str_field()));

Or to move into a new string:

    std::string result = std::move(*my_msg.mutable_my_str_field());

There are already rvalue overloads of setters, constructors and assignment operators for strings, singular message fields and all repeated containers. Combined with `mutable_*` methods, this should give you what you want.

As pherl mentioned, you can alternatively use the `release_*` methods, which existed before move semantics were added to protobufs:

    destination_msg.set_allocated_my_str_field(source_msg.release_my_str_field());
    std::unique_ptr<std::string> result(another_msg.release_my_str_field());

These can be a bit more efficient for messages, because they change a single pointer rather than moving each of the fields individually. But I imagine the difference is not noticable unless you have a message with hundreds of fields, and perhaps not even then. Besides, `release_*` does a deallocation whereas a move would preserve the footprint of the message, which may save a later allocation.

For singular messages, yet another alternative is the `Swap()` method.

At a higher level, consider passing the whole protobuf object around rather than moving lots of individual fields. For example, if you have a protobuf `UserData` with 10 fields, and a class you've hand written called `User` with the same 10 fields plus a few more and some methods, consider having `UserData` be stored directly in the `User` class instead. You can use the message's move constructor to make construction of `User` efficient. This idea doesn't work for all applications, but can simplify code a lot when it does.
