### ISSUE TITLE
How PB handle duplicate references?

### ISSUE THREAD

**Issue by AaronLiang** [google/protobuf#4453]
If we have some duplicated objects in the body, they have the same reference. will bp serialize them in multiple times or only once?

**Comment by acozzette** [comment]
@AaronLiang Which language are you using?

**Comment by AaronLiang** [comment]
@acozzette   I am using java and C#

**Comment by acozzette** [comment]
@AaronLiang In Java if you assign the same reference for multiple message fields, this is fine and they will just be treated as if they were separate objects (the same data will be serialized in multiple places).

@jskeet @anandolee Do you know the answer to this question for C#? I would guess that having multiple submessage fields which alias each other would cause problems for C# protos since they are mutable.

**Comment by jskeet** [comment]
Yes, in C# the same data will be serialized multiple times too. If you have:

```text
message Foo
{
    Bar b1 = 1;
    Bar b2 = 2;
}

message Bar
{
    int x = 1;
    int y = 1;
}
```

and then in C# write:

```csharp
var bar = new Bar();
var foo = new Foo { B1 = bar, B2 = bar };
bar.X = 10;
bar.Y = 10;
```

then yes, when you serialize `foo` you'll get (10, 10) for both `b1` and `b2`, but you'll get the data separately. I'm not sure I'd say that's a problem per se - it's how I'd expect it to work with regular C# classes.

There's nothing in the serialization protocol to say "look at that field over there" though, so it's not like we have an option,

**Comment by acozzette** [comment]
Thanks @jskeet!
