### ISSUE TITLE
From 3.0 to 2.5

### ISSUE THREAD

**Issue by met666** [google/protobuf#4461]
How can I degrade my protobuf to 2.5 from 3.0?
Windows 10. Thanks for the help in advance.

**Comment by acozzette** [comment]
@met666 Are you using `syntax = "proto3"` in any .proto files? If so then you won't be able to downgrade. But otherwise, you should be able to just switch to using protobuf 2.5 because there is no difference in the wire format.

Why do you want to downgrade, though? With every release we fix bugs and add performance improvements and so you would probably have better results using the most recent version you can.
