### ISSUE TITLE
protobuf 反序列化的时候怎么解析对应的message对象

### ISSUE THREAD

**Issue by Tgsgf** [google/protobuf#4490]
多个message序列化后通过socket发送，接收方要怎么才能对应反序列化对象？  网上搜了一下说给包体加头部，接收方通过头部反序列化；我个人觉得这个方法封包拆包的时候会创建和删除内存，效率有点低，我想问问有没有protobuf有没有什么好方法能够快速反序列化呢？

**Comment by TeBoring** [comment]
Your client code are supposed to know how to decode message. It should have linked the same proto definition as the server does.

**Comment by TeBoring** [comment]
BTW, what language are you using?

**Comment by Tgsgf** [comment]
服务端用C++， 客户端用C#

**Comment by Tgsgf** [comment]
@TeBoring 服务端用C++， 客户端用C#，序列化和反序列化单个message对象是可以的,但是socket信道上传输多个message对象要怎么对应去反序列化它

**Comment by xfxyjwf** [comment]
Protobuf can only be parsed if the type is known by the receiver. If you send different types of protos over the wire, you must accompany the data with some identification information so the receiver can tell what proto type it has received. The commonly used techniques are:
1. Embed the type name in a header with proto serialized bytes as the payload. RPCs generally take this approach, although they usually encode the rpc method name instead of proto type name, but the type name can be inferred from the method name.
2. Use one single proto type on the wire and put everything you want in this one single type. For example, you can declare a message with an oneof:
```proto
message Request {
  oneof oneof_request {
    SearchRequest search = 1;
    ChatRequest chat = 2;
    // ...
  }
}
```

**Comment by Tgsgf** [comment]
@xfxyjwf 
Thank you for your reply, the method should be suitable for me, but I don't understand "Embed the type name in a header with proto serialized bytes as." is it serialized first or after adding head or head, to be serialized, can give a specific example?
