### ISSUE TITLE
Java DynamicMessage Parsing Sets 0.0 Double Values to NULL

### ISSUE THREAD

**Issue by westonsankey** [google/protobuf#4503]
When parsing the binary representation of an object into a DynamicMessage using the object's descriptor, any Double field set to 0.0 will be set as `NULL`. This results in the field not being included in the DynamicMessage field list. 

```java
MyProto proto = MyProto.newBuilder()
    .setSampleField(0.0)
    .build()

try {
    Descriptors.Descriptor descriptor = MyProto.getDescriptor();
    DynamicMessage message = DynamicMessage.parseFrom(descriptor, proto.toByteArray());
    Map<Descriptors.FieldDescriptor, Object> fields = message.getAllFields();
    assert fields.size() == 1 // Assertion fails
} 
catch (InvalidProtocolBufferException ex) {
    ex.printStackTrace();
}

```
The example is based off of the following protobuf definition. The issue appears to be exclusive to the proto3 syntax; when using proto2 syntax and setting the field as `optional`, it parses correctly.
```
syntax = "proto3";

message MyProto {
    double sample_field = 1;
}
```

**Comment by xfxyjwf** [comment]
This is working as intended. In proto3, setting a field to its default value has the same effect as clearing the field. See:
https://developers.google.com/protocol-buffers/docs/proto3#default

If you call `proto.getAllFields()`, it should return an empty map as well. If it doesn't, that's a bug in the implementation.

**Comment by dpauls** [comment]
I know this is an old, closed issue, but I have exactly the same question so I'm hoping it's ok to extend this discussion here. I'm also interested if the introduction of `optional` into proto3 (which didn't exist in 2018) might change any views on this?

I also view the behaviour described by @westonsankey as a bug, but I suppose it comes down to whether the intent is to:
* Get all values present on the wire
* Get all values semantically conveyed with the message.

The docs for `getAllFields` aren't very clear on this. If I strip the parts of the docs related to required, optional, and repeated fields (none are the case in the posted example), it says the following (emphasis mine):
> Returns a collection of all the fields in this message which are **set** and their corresponding values. The values are exactly what would be returned by calling [MessageOrBuilder.getField(Descriptors.FieldDescriptor)](https://developers.google.com/protocol-buffers/docs/reference/java/com/google/protobuf/MessageOrBuilder.html#getField(com.google.protobuf.Descriptors.FieldDescriptor)) for each field.

What is meant by the word **set**? The parser has no way of knowing if the value was set or not if the field doesn't have [explicit field presence](https://github.com/protocolbuffers/protobuf/blob/main/docs/field_presence.md#presence-in-proto3-apis). The value could have been set to the default value, but then not encoded on the wire, knowing the semantics are that the parsed message should provide the default value as the value for that field. If this is the meaning of "set" here, it seems impossible to implement.

Alternately, the definition of **set** could be "serialized in the message". If this is the intention, then it seems the existing implementation is correct, but not particularly useful since it doesn't convey the information the sender intended to convey.

What I would propose is **set** in the context of the `getAllFields()` description meant:
* For fields with explicit field presence, all values whose hazzer returns true.
* For fields without explicit field presence, return the default value.

Perhaps to avoid breaking any user relying on the existing interface, there could be a separate (or overloaded) method that used these semantics. Would this make sense?

**Comment by fowles** [comment]
At this point, we do not wish to change the semantics of the existing method (for the reasons noted by you).  We also don't want to add a new interface with a new semantic because new methods have a surprisingly high cost in terms of the volume of generated code and as a consequence final size for binaries.
