### ISSUE TITLE
Generated code to use std::vector<> instead of RepeatedPtrField<>

### ISSUE THREAD

**Issue by alulla** [google/protobuf#4526]
It would be nice if protoc could generate code that uses std::vector<> instead of RepeatedPtrField.  This will allow us to swap vectors in/out of the proto message as many programs use std::vector.

To ease backwards compatibility, an option to protoc can be leveraged in order to generate std::vector<> stubs.  I know it seems like a decent amount of work, but I know it will help performance in my use case.

Also, I know there is some discussion regarding c++'11 support and adding the ability to support move semantics, but in my use case leveraging std::vector<> would help in addition to c++'11 support.

**Comment by xfxyjwf** [comment]
This won't happen because:
1. It requires an API breaking change to protobuf reflection API where repeated fields are exposed as RepeatedField/RepeatedPtrField and won't work if the implementation has been changed to anything else.
2. std::vector or any other type that isn't part of protobuf library won't work with protobuf arena. We explicitly decided to use proto2::Map instead of std::map/unordered_map to implement map fields because of this and we are not going to revert it to std::map/unordered_map. Neither will we replace RepeatedField/RepeatedPtrField with std::vector (or any other std:: container type as long as the type is not under our total control) for the same reason.
3. We hate more options.

Note that the amount of work to implement a feature is usually the least that we are concerned about. Compared to the time/effort required to adapt everyone to a new feature (e.g., update every protobuf reflection based library to be aware of a possible alternative std::vector representation for repeated fields), implementing a feature in protobuf alone takes pretty much no time or effort.
