### ISSUE TITLE
Objective-c not support utf8mb4

### ISSUE THREAD

**Issue by ysk666666** [google/protobuf#4528]

**Comment by thomasvl** [comment]
Could you explain what the question/problem is?  I'm assuming this is in reference to `string` fields?  ObjC protos uses the Foundation `NSString` class for strings so that they interop with everything else on the Apple platforms that want strings, so if there is an issue, it likely will be at the Foundation layer.

**Comment by ysk666666** [comment]
@thomasvl i found if message contains emoji（it is 4 bits of  utf8），it will
`    if (!result) {
#ifdef DEBUG
      // https://developers.google.com/protocol-buffers/docs/proto#scalar
      NSLog(@"UTF-8 failure, is some field type 'string' when it should be "
            @"'bytes'?");
#endif
      RaiseException(GPBCodedInputStreamErrorInvalidUTF8, nil);
    }`
I don't know the reason

**Comment by thomasvl** [comment]
Can you provide a binary dump of the message and what the proto definition was so we can try to recreate it?  Also, which language was used to create the message?

The error could be that the first language allowed something into a message that wasn't valid in the first place.

**Comment by ysk666666** [comment]
@thomasvl 
i am sorry, Outside working hours, i creat a demo it working properly, whether it is proto2 or proto3.
it may my company project has other issues.
sorry about created this issue, you can close it. Thank you!

**Comment by thomasvl** [comment]
No problem, thanks for getting back to us.
