### ISSUE TITLE
Cygwin build failed

### ISSUE THREAD

**Issue by chronoxor** [google/protobuf#4575]
Cygwin build failed with a following error:

/cygdrive/c/projects/cppserialization/modules/protobuf/src/google/protobuf/compiler/command_line_interface.cc: In function ‘bool google::protobuf::compiler::{anonymous}::GetProtocAbsolutePath(std::string*)’:
/cygdrive/c/projects/cppserialization/modules/protobuf/src/google/protobuf/compiler/command_line_interface.cc:205:56: error: ‘readlink’ was not declared in this scope
   int len = readlink("/proc/self/exe", buffer, PATH_MAX);
                                                        ^

**Comment by acozzette** [comment]
Does the error go away if you include `<unistd.h>` at the top of the file? There's an include for that [here](https://github.com/google/protobuf/blob/0869b1a0a7455dab94981aa29b8bfb69444fa13e/src/google/protobuf/compiler/command_line_interface.cc#L51) already, but it's guarded by an ifdef and I'm not sure if it would apply in a Cygwin environment.

The other possibility is that perhaps we want to use `GetModuleFileNameA` instead of `readlink` on Cygwin, which is controlled by another ifdef here: https://github.com/google/protobuf/blob/0869b1a0a7455dab94981aa29b8bfb69444fa13e/src/google/protobuf/compiler/command_line_interface.cc#L192

**Comment by chronoxor** [comment]
Fixed the issue with

#ifndef _GNU_SOURCE
#define _GNU_SOURCE
#endif

at the begin of the command_line_interface.cc

See https://github.com/google/protobuf/pull/4583

**Comment by chronoxor** [comment]
Fixed!
