### ISSUE TITLE
Is it possible to reference an inner message from a different package?

### ISSUE THREAD

**Issue by wvxvw** [google/protobuf#4594]
Consider you have these two files:

`Foo.proto`:

``` protobuf
package Foo;

message Foo {
    message Foo {
        int32 foo = 1;
    }
}
```

`bar.proto`:

``` protobuf
package bar;

import "Foo.proto";

message Bar {
    Foo foo1 = 1;
    Foo.Foo foo2 = 2;
    Foo.Foo.Foo foo3 = 3;
}
```

Is `Bar` definition valid? If not, which fields are not valid? What will be in those fields? The published language spec says nothing about it. (I just assumed that in order to refer to the inner message definition you'd use dot, but I don't know, maybe it should be `$` or some other symbol, again, language spec says nothing about it.

----

I found this in the docs:

> If you want to reuse this message type outside its parent message type, you refer to it as Parent.Type: 

```
message SomeOtherMessage {
  SearchResponse.Result result = 1;
}
```

But it doesn't say if this is possible to do from a different package, and this ignores the obvious problem: what if you have  a package called `Foo.Foo`, and a message definition in package `Foo`, called `Foo`.  What takes precedence? Is this legal?

**Comment by xfxyjwf** [comment]
Protobuf follows C++ name resolution rules and every symbol must have a globally unique fully-qualified name. So:
1. "Foo foo1 = 1" is invalid because "Foo" references the package which can't be used as a message type.
2. "Foo.Foo foo2 = 2" and "Foo.Foo.Foo foo3 = 3" are valid and they reference the outer "Foo" message and the inner "Foo" message defined in "foo.proto".
3. You can't have a package and a message both named "Foo.Foo".

If you change the package of "bar.proto" to "Foo" as well:
1. "Foo foo1 = 1" and "Foo.Foo foo2 = 2" are valid and reference the outer "Foo" and inner "Foo" respectively.
2. "Foo.Foo.Foo foo3 = 3" will become invalid because it will resolve to "Foo.Foo.Foo.Foo" according to C++ name resolution rules and that type doesn't exist.

Besides proto language rules, the generated code is also subject to the rules of the programming language it's generated for. In this regard, protoc does not guarantee the generated code to be compilable and I'm pretty sure some programming languages don't allow a "Foo" class nested in a parent class with the same name "Foo".

**Comment by xfxyjwf** [comment]
Closing this issue as I think your question has been answered. Feel free to create an issue requesting for more thorough documentation of the language spec. @anandolee FYI.
