### ISSUE TITLE
iOS generated code for descriptor.proto, Descriptor.pbobjc.h not found

### ISSUE THREAD

**Issue by hchosc** [google/protobuf#4685]
Generated code for descriptor.proto doesn't exist. This exists for Java.

**Comment by thomasvl** [comment]
Not all the languages ship the generated file for `descriptor.proto`, the ones that do, do so because the use them within the runtime support for the library.  Objective C is one of the languages that doesn't need them (and doesn't capture the binary descriptor blob either), so the file is left of to cut down on the size runtime support.  If you have a need for the types, you can always ship generate it and ship it yourself.

**Comment by acrabb** [comment]
where can we find a `descriptor.proto` file to use with objective c if we need one?

**Comment by thomasvl** [comment]
It is in this project - `src/google/protobuf/descriptor.proto`
