### ISSUE TITLE
different md5sum for protoc?

### ISSUE THREAD

**Issue by g10guang** [google/protobuf#4832]
After I exec `make && make install`, I check md5sum for protoc:

```
g10guang@VM-206-139-ubuntu:~/lib/protobuf-3.6.0/src$ md5sum ./protoc 
564f97ee7a10d9516b617ca473a54fe1  ./protoc
```

```
g10guang@VM-206-139-ubuntu:~/lib/protobuf-3.6.0/src$ md5sum `which protoc`
77ede5a37a38fbd44fe32c38546d2a39  /usr/local/bin/protoc
```

```
g10guang@VM-206-139-ubuntu:~/lib/protobuf-3.6.0/src$ protoc --version
libprotoc 3.6.0
g10guang@VM-206-139-ubuntu:~/lib/protobuf-3.6.0/src$ ./protoc --version
libprotoc 3.6.0
```

What's up?

Can anybody tell me they are different or not?

If their different, please show me the difference.

**Comment by acozzette** [comment]
If I remember right, `make` will actually put a wrapper shell script at `src/protoc`--I'm not sure why but I think it has something to do with setting up the environment properly so that the real binary knows where to find `libprotobuf` and `libprotoc`. But `make install` will put the real binary in `/usr/local/bin`. So the likely reason for the md5sum difference is that one file is a shell script while the other is a real binary.
