### ISSUE TITLE
Duplicate custom option names generate compiler error

### ISSUE THREAD

**Issue by wittmeie** [google/protobuf#4861]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: C++

**What operating system (Linux, Windows, ...) and version?**
Linux, Ubuntu 16.04

**What runtime / compiler are you using (e.g., python version or gcc version)**
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609

**What did you do?**
Generated two custom options, one for messages and for services with the same name.
```proto
syntax = "proto2";

import "google/protobuf/descriptor.proto";

message StringList {
  repeated string elements = 1;
}

extend google.protobuf.MessageOptions {
  optional StringList list = 51235;
}

extend google.protobuf.ServiceOptions {
  optional StringList list = 51235;
}
```

**What did you expect to see?**
No protoc error.
The protobuf documentation states that even the field numbers of custom option types can be identical. Why not the field names?

> Also, note that each option type (file-level, message-level, field-level, etc.) has its own number space, 
 so e.g. you could declare extensions of FieldOptions and MessageOptions with the same number.

**What did you see instead?**
[  1%] Running cpp protocol buffer compiler on customoptions.proto
customoptions.proto: "list" is already defined.

Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Anything else we should know about your project / environment**

**Comment by xfxyjwf** [comment]
Your proposal can't be implemented. The name of the extension will be used as the name of the generated extension identifier. For extensions in the same scope their generated extension identifiers will be put inside the same scope in the generated code as well (e.g., in the same C++ namespace, or in the same Java class). If two extensions have the same name, their generated extension identifiers will have the same name and the generated code won't compile. We cannot change this because how and where the extension identifiers are generated is part of protobuf public API.
