### ISSUE TITLE
C#: Missing Runtime Types for descriptor protos

### ISSUE THREAD

**Issue by MHDante** [google/protobuf#4926]
**What version of protobuf and what language are you using?**
Version: v3.6.0
Language: C#

**What operating system (Linux, Windows, ...) and version?**
Windows

**What runtime / compiler are you using (e.g., python version or gcc version)**
Protobu-Tools from NuGet

**What did you do?**

Compile the following proto for C#:

``` protobuf
syntax = "proto3";

import "google/protobuf/empty.proto";
import "google/protobuf/descriptor.proto";

package ReflectionMessage;

service TypeServer {
    rpc RequestType (.google.protobuf.Empty) returns (Test);
}

message Test{
    .google.protobuf.DescriptorProto first = 1;
}
```

**What did you expect to see**

Compilable C#

**What did you see instead?**

The type in the C# file is inaccessible.

`obj\gen\TypeService.cs(82,47): error CS0122: 'DescriptorProto' is inaccessible due to its protection level`

----------------

The runtime type for the messages in descriptor.proto are inaccessible. I would like to use them in order to have access to things such as Source Code information. 

1) If possible since DescriptorProto is a WellKnownType, can the C# representation of it be non-internal? This would be the best solution for my use case. I would eventually need to access the leading/trailing Comments.

2) However, I realize that there is a public representation for these already. `*Descriptor.cs`. Another solution would be to use the the `MessageDescriptor` instead of DescriptorProto, However, they have less definition (They are missing SourceCode information)

**Comment by anandolee** [comment]
MessageDescriptor is the runtime type for descriptor proto. What information do you need but is missing in MessageDescriptor?

**Comment by anandolee** [comment]
I assume DescriptorProto is changed to internal because some proto2 features are not supported.

The access level is change in:
https://github.com/google/protobuf/commit/493e3db98532e99a53cec914d8f4827a556ee408#diff-40a612bde80077a230c176f78b24b669

@jskeet , do you remember why descriptor protos should be private? Are we safe to change it to public or it should wait for proto2 support.

**Comment by jskeet** [comment]
No, we should **not** change them to be public. They're generated as if they were proto3, but only because we know that within Google.Protobuf we don't care about the different semantics.

Additionally, we wouldn't want to expose the DescriptorProto instances directly due to mutability.

If we implement proto2, we can make DescriptorProto public, and we could then return clones from the Descriptor class etc.

**Comment by MHDante** [comment]
So then, should protoc CSharp generation refer to the appropriate run-time representations instead? In other words, should it convert `DescriptorProto` to `MessageDescriptor` much like how the `Int32Value` members get converted to System.Nullable<int>?

**Comment by jskeet** [comment]
No, I don't think that would be appropriate either. Basically, using `DescriptorProto` depends on implementing the proto2 features (and then cloning, but that's relatively straightforward). Until that point, I wouldn't expect you to be able to use the message in your first comment.

**Comment by anandolee** [comment]
As proto2 is not supported, we are unable to make them public or provide a run-time representation. @ObsidianMinor is working on proto2 support, we can make DescriptorProto public after that.

Closing this issue for clean up. Feel free to reopen after proto2 is supported or if you have any other questions.
