### ISSUE TITLE
Is there a reason, not to use a different name space for protobuf 3

### ISSUE THREAD

**Issue by vishalsan** [google/protobuf#507]
If google wants  to support both 2 and 3, it would be highly desirable that the namespace ( package declaration has v3 in it) is different. That would allow protobuf 2 and 3 to coexist. I today am not able to run protobuf 3 on platforms that have bootstrap dependencies on protobuf 2 ( hadoop is an example ) 

https://hadoop.apache.org/docs/r2.6.0/hadoop-project-dist/hadoop-common/dependency-analysis.html

**Comment by xfxyjwf** [comment]
They share the same namespace because they share most part of the implementation. It's proto2 with some modifications, rather than a new thing created from scratch.

Regarding the binary compatibility, in future releases, we will try to ensure the code generated by an old protoc can work with newer versions of the proto runtime.
