### ISSUE TITLE
Expected Identifier Error with 2.6.1 on Mac OS X 10.10

### ISSUE THREAD

**Issue by dustinwilson** [google/protobuf#549]
I get this error when compiling Spectrum XMPP Transports:

```
In file included from /usr/local/include/google/protobuf/message.h:120:

/usr/local/include/google/protobuf/descriptor.h:358:5: error: expected identifier

    TYPE_BOOL           = 8,   // bool, varint on the wire.

    ^

/usr/include/ConditionalMacros.h:147:39: note: expanded from macro 'TYPE_BOOL'

     #define TYPE_BOOL
```

It's an error that's caused because TYPE_BOOL is already defined in ConditionalMacros.h on OS X. In the 3.0.x alphas you've fixed this already by adding:

```C++
// TYPE_BOOL is defined in the MacOS's ConditionalMacros.h.
#ifdef TYPE_BOOL
#undef TYPE_BOOL
#endif  // TYPE_BOOL
```

However in 2.6.x it hasn't been applied there. I'd rather not use alpha software on a production machine. I've patched my local header file, and it fixes the compilation issue. Could you add it to 2.6.x as well while we wait for 3.0 to mature?

**Comment by xfxyjwf** [comment]
For 2.6.x, we probably will not make new releases.

The version number has been alpha because we have some more languages to support. If you are using C++/Java/Python, they are mature enough and can be relied on. Internally in Google they are already used on production machines before changes are merged to this github repo.

**Comment by dustinwilson** [comment]
Okay. Thanks! I'll just use the latest alpha then.

**Comment by yijiem** [comment]
While this issue is fixed now, a similar situation happens when I tried to extend FieldOptions in my proto file. Basically, I import https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.proto in my.proto file. Then, after compile, my.pb.h includes the pre-compiled https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.pb.h which does not have the `undef TYPE_BOOL` fix in https://github.com/google/protobuf/blob/master/src/google/protobuf/descriptor.h. So I ended up with the same compilation error.
