### ISSUE TITLE
two different versions of protobuf-2.5.0.tar.gz: one works, one doesn't

### ISSUE THREAD

**Issue by demianturner** [google/protobuf#564]
This screengrab hopefully summarises the problem, big wtf as one wouldn't suspect the 2 files to be different.  The one that doesn't work doesn't have the required *configure* script.

![protobuf3](https://cloud.githubusercontent.com/assets/136587/8457231/1e0182e0-2008-11e5-80a5-4709c5b5dcee.png)

**Comment by xfxyjwf** [comment]
I know this is confusing but the download link you see in the first snapshot is not provided by us. It's provided by github and just a copy of the code in the git repository rather than a release version.

In the second snapshot, you can also see two other links "Source code (zip)" and "Source code (tar.gz)". These are also provided by github and does not have the configure file as well.

**Comment by demianturner** [comment]
I took the time to highlight the problem because it wasted about 1 hr of my time.  Thought it would be useful to future users of your software.

**Comment by xfxyjwf** [comment]
Sorry for that. I'm contacting github support to see if there is an option to disable those archive links.

**Comment by xfxyjwf** [comment]
Just got a reply from github support team that such an option doesn't exist yet so we will have to bear with these extra download links for the time being.

In the beginning of the [README.md](https://github.com/google/protobuf/blob/master/README.md) file we have mentioned what users are expected to do if they get a package without gmock and configure script. Feel free to give us suggestions if you think the current text is not clear enough.

**Comment by demianturner** [comment]
I think you'll always get users that focus on the INSTALL.txt rather than the README.  Maybe add a sentence to the INSTALL file that says what to do if the configure script is missing.  Cheers.
