### ISSUE TITLE
Update addressbook.proto, tutorial code and documentation

### ISSUE THREAD

**Issue by jskeet** [google/protobuf#565]
Currently addressbook.proto is proto2.
We should either update it to proto3, or create a new equivalent for proto3. This should follow the new repeated fields naming convention of using plurals.

The csharp_experimental branch will soon have a proto3 version which has *just* removed the proto2 aspects of the file - we should consider this carefully before merging into master.

**Comment by jtattermusch** [comment]
@xfxyjwf @anandolee, should everyone be using the proto3 version of the file in the future?
If not, we can just add a proto3 specific version of addressbook.proto.

If we want everyone to migrate to proto3 addressbook (which shouldn't be hard, because the addressbook examples are pretty simple), we should probably do this work in upstream/master first and then pull this change into csharp-experimental  rather than the other way round (we don't want too many unrelated changes in the big PR to merge C# to master, because it's going to be big enough).

**Comment by xfxyjwf** [comment]
The examples directory is intended to show users how to build their project with protobuf (also to verify that protobuf installation works). We don't need to cover every API version there. As we are advocating proto3, changing addressbook.proto to proto3 seems good to me.

**Comment by jtattermusch** [comment]
#628

**Comment by jtattermusch** [comment]
https://github.com/google/protobuf/pull/628
