### ISSUE TITLE
MSAN failure in StatusOr

### ISSUE THREAD

**Issue by AustinSchuh** [google/protobuf#693]
I built the protobuf compiler and test suites today with the MemorySanitizer in Clang, and ran into an issue with uninitialized variables in protobuf/src/google/protobuf/stubs/statusor_test.cc.

Both StatusOr.TestPointerCopyCtorStatusNotOkConverting and StatusOr.TestPointerAssignmentStatusNotOkConverting are failing.  It looks like they are failing because value_ isn't initialized in the first StatusOr<>.  When you convert a Derived* to a Base2*, it then triggers the compiler to modify the pointer and that looks like it triggers the failure.

I don't think this is a real issue, but I'm not sure.  Any advice?

**Comment by xfxyjwf** [comment]
value_ is not intialized if the status is not ok. That seems fine to me. Is there any annotation we can add to protobuf code to suppress such errors?

**Comment by AustinSchuh** [comment]
@brian-peloton  Would that work?

**Comment by brian-peloton** [comment]
I think it might be undefined behavior, which means suppressing the warning isn't the right thing to do. Looking around online didn't yield anything definitive, but it doesn't seem like a good thing to be doing.

The problem seems to be that the compiler has to insert a branch based on whether the pointer is NULL or not (to avoid changing NULL to not-NULL). An uninitialized pointer could change from not-NULL to NULL, which is kind of weird but seems unlikely to be an issue. However, accidentally wrapping a pointer value could definitely have actual effects on the behavior of the code, which seems to me like enough reason to fix this. Optimizers like making assumptions about arithmetic not overflowing to avoid inserting mask operations, which this issue violates.

I just submitted a pull request (#1162) I've been meaning to send for a while which fixes this by not copying the pointer if !ok(). It shouldn't have any detectable effect on performance and completely fixes this issue.
