### ISSUE TITLE
Protobuf 2.6.0 incompatibility issues with Python 3.x

### ISSUE THREAD

**Issue by KJaunay** [google/protobuf#7]
I've run into a problem when using Python 3.4 and protobuf 2.6.0. 
I get several errors including:
protobuf/python/google/protobuf/internal/decoder.py, line 167
  _DecodeVarint = _VarintDecoder((1 << 64) - 1, long)
  NameError: name 'long' is not defined

**Comment by tseaver** [comment]
FWIW, #164 modernizes the `python` code to drop all the PY25 stuff.

**Comment by thanatos** [comment]
Why is this bug marked as Closed & obsolete? I'm currently trying to get a third-party package (`heka_py`) that uses protobuf to work, and near as I can tell, [the latest version is not Python 3 compatible](https://github.com/google/protobuf/blob/v2.6.1/python/google/protobuf/internal/python_message.py#L848).

There's a package `python3_protobuf` on PyPI (I have no idea if this is official or not) but it is on Protobuf 2.5, and unfortunately Heka assumes 2.6.

**Comment by jleclanche** [comment]
@thanatos https://pypi.python.org/pypi/protobuf `pip install protobuf==3.0.0b3` is python3-compatible.

**Comment by thanatos** [comment]
> @thanatos https://pypi.python.org/pypi/protobuf `pip install protobuf==3.0.0b3` is python3-compatible.

While technically true, my understanding is that the major number here is bumped because it isn't backwards-compatible with compiled protocol buffers from protobuf v2; empirically, this seems to be the case; e.g., `<a Message derived class>.INTEGER` doesn't exist in protobuf==3.0.0b3.

**Comment by xfxyjwf** [comment]
On Fri, Jul 15, 2016 at 2:41 PM, Roy Wellington Ⅳ <notifications@github.com>
wrote:

> @thanatos <https://github.com/thanatos>
> https://pypi.python.org/pypi/protobuf pip install protobuf==3.0.0b3 is
> python3-compatible.
>
> While technically true, my understanding is that the major number here is
> bumped because it isn't backwards-compatible with compiled protocol buffers
> from protobuf v2; empirically, this seems to be the case; e.g., <a
> Message derived class>.INTEGER doesn't exist in protobuf==3.0.0b3.
>
We bumped the major version number because of the new proto3 syntax
support, not because it's incompatible. If you find incompatible issues
with old generated code, please help file a bug for it.

**Comment by Laowai01** [comment]
i have compiled caffe on Ubuntu 16.04 LTS both with python 2 and python, it is really a hectic process for beginners, for caffe with python 2.7 make sure that your /.local/lib/python2.7/site-packages only contains a version same as you protoc version. protoc version can be checked by entering
`protoc --version`
for me i got problems with python 2.7 because by mistake i installed protbuf 3.0 alpha in python 2.7 site packages, so there was a protobuf error after removing it from python 2.7 site packages everything worked fine
also install python-dev version
`apt-get install the python3.x-dev`
and for python 3.5 make sure you have python 3.0 alpha, if you have both python 2.7 and python 3.x in the system use pip3 otherwise use pip

`pip3 install protobuf==3.0.0-alpha-3`

or another protobuf such as 3.5 version of protobuf.
also do this
`pip3 install python-dateutil --upgrade`
after that do 
`make clean`
`make all`
`make runtest`
`make pycaffe`
after performing make all make runtest steps don't forget to do that
`sudo ldconfig`

hope everything works OK for you.
