### ISSUE TITLE
confusing interaction between -I and --cpp_out arguments

### ISSUE THREAD

**Issue by brathke** [google/protobuf#723]
I have the following directory structure
```
(master)$ tree
.
├── Makefile
├── protofiles
│   ├── Base
│   │   └── Base.proto
│   ├── CategoryA
│   │   └── MessageA1.proto
│   ├── CategoryB
│   │   └── MessageB1.proto
│   └── CategoryC
│       └── MessageC1.proto
└── README.md
```

I compile MessageA1.proto as follows, and get expected results (.pb.h and .ph.cc in the same directory as the .proto file)
```
(master)$ protoc --cpp_out=. protofiles/CategoryA/MessageA1.proto 
(master)$ tree
.
├── Makefile
├── protofiles
│   ├── Base
│   │   └── Base.proto
│   ├── CategoryA
│   │   ├── MessageA1.pb.cc    <------------- ok
│   │   ├── MessageA1.pb.h     <-------------- ok
│   │   └── MessageA1.proto
│   ├── CategoryB
│   │   └── MessageB1.proto
│   └── CategoryC
│       └── MessageC1.proto
└── README.md
```

Now I add an include path, and the output files show up in a different directory.
```
(master)$ protoc -I=protofiles/CategoryA --cpp_out=. protofiles/CategoryA/MessageA1.proto 
(master)$ tree
.
├── Makefile
├── MessageA1.pb.cc              <------------ ???
├── MessageA1.pb.h               <------------ ???
├── protofiles
│   ├── Base
│   │   └── Base.proto
│   ├── CategoryA
│   │   └── MessageA1.proto
│   ├── CategoryB
│   │   └── MessageB1.proto
│   └── CategoryC
│       └── MessageC1.proto
└── README.md
```

Now I change to a different include path, and the output files move again.
```
(master)$ protoc -I=protofiles --cpp_out=. protofiles/CategoryA/MessageA1.proto 
(master)$ tree
.
├── CategoryA                           <------------ ???
│   ├── MessageA1.pb.cc          <------------ ???
│   └── MessageA1.pb.h            <------------ ???
├── Makefile
├── protofiles
│   ├── Base
│   │   └── Base.proto
│   ├── CategoryA
│   │   └── MessageA1.proto
│   ├── CategoryB
│   │   └── MessageB1.proto
│   └── CategoryC
│       └── MessageC1.proto
└── README.md
```

I didn't expect this interactivity btw -I and --cpp_out.  Is this expected behavior?

**Comment by xfxyjwf** [comment]
Try:
```
(master)$ protoc -I=protofiles --cpp_out=protofiles protofiles/CategoryA/MessageA1.proto 
```
and in your proto files, import the other protos like this:
```
syntax = "proto3";
import "Base/Base.proto";
....
```

This should work for all your proto files.

**Comment by xfxyjwf** [comment]
This is the expected behavior. Let me try to explain.

Quite different from C++, in protobuf, a .proto file must be imported using exactly the same name from all proto files, or the generated code will not compile (likely link error if you manage to prevent protoc from complaining about "file not found"). Let's call this name a .proto file's canonical name. The "-I" flag does more than just specifying an import path: it also defines a mapping from a file's disk path to its canonical name. For example, if you specify "-I=protofiles", you are telling the compiler that a disk file "protofiles/Base/Base.proto" has the canonical name "Base/Base.proto" and should be imported with such a name. When the compiler generates C++ code for the proto file, it will also use the canonical name to determine the output files' layout. For example:
```
(1) $ protoc --cpp_out=. protofiles/CategoryA/MessageA1.proto
(2) $ protoc -I=protofiles --cpp_out=. protofiles/CategoryA/MessageA1.proto
```
In example (1), the canonical name of the file is "protofiles/CategoryA/MessageA1.proto" so you need to import it as "protofiles/CategoryA/MessageA1.proto" from other files and the compiler will generate protofiles/CategoryA/MessageA1.pb.h. In example (2), the canonical path of the file is "CategoryA/MessageA1.proto", so you need to import it as "CategoryA/MessageA1.proto" and the compiler generates CateogryA/MessageA1.pb.h

If you run protoc on each of your proto files separately, it's important to specify the "-I" flag consistently. For example:
```
(3) $ protoc --cpp_out=. protofiles/Base/Base.proto
(4) $ protoc --cpp_out=. protofiles/CategoryA/MessageA1.proto
(5) $ protoc -I=protofiles --cpp_out=protofiles protofiles/CategoryB/MessageB1.proto
```
If both A1.proto and B1.proto import Base.proto, you will never get the generated code compiled because A1.proto assumes the canonical name of Base.proto to be "protofiles/Base/Base.proto" while B1.proto assumes it's "Base/Base.proto". The generated code will reference the same symbol using different names and only one of them can possibly compile.

This is not easy to get right. For most users, I think it's better to just not use this flag and put all proto files in a single directory tree and compile all of them with a single protoc invocation. Use "-I" only when you need to import proto files from another project.

**Comment by brathke** [comment]
Thanks! I appreciate the helpful explanation.
