### ISSUE TITLE
When set type is not equal the define type ,protobuf will crash.

### ISSUE THREAD

**Issue by cijianzy** [google/protobuf#729]
When I set NSMutableDictionary type to the NSString, the [XXX data] method will crash in
   
     - (size_t)serializedSize 

method in the 2804 line of GDBMessage.h.

I do not want it crash , It is will be nice  that it like 

    [xxxx parseFromData:result error:error];

It will  catch the error and let I know.

Forgive my English. THX

**Comment by thomasvl** [comment]
GDBMessage.h doesn't exist, assuming you mean GPBMessage.h, but that also doesn't have a line 2804.

What is the change you are making to get thing to crash and why are you making that change?

**Comment by cijianzy** [comment]
Sorry ,It is GDBMessage.m , when the "result" was broken or not the right format , it will be crash , i do not want crash.So I want the method "parseFromData" catch the error and do not crash.

**Comment by thomasvl** [comment]
How'd you get the wrong time in there in the first place?

Generally ObjC classes don't protect against someone casting the wrong type and passing it into an api.

**Comment by thomasvl** [comment]
fyi - GDBMessage (.h or .m) doesn't exist in this project.

Line 2804 doesn't really map to something reasonable in the current version of GPBMessage.m.

I'm going to close, because it is sounds like it is coming down to forcing a string onto a property that is supposed to be a dictionary.  Objective C code usually isn't defensive against this, as forcing the wrong type is the developer sorta going out of there way to do something wrong.

If you can provide a code example showing how you can get the wrong type in there without it being a programming error, please reopen and we can see if there is something we can do to improve the library.
