### ISSUE TITLE
MSVC: Doesn't link with disabled language extensions

### ISSUE THREAD

**Issue by githubacc32** [google/protobuf#774]
Hello,

Is it really necessary to use non-standard functions? I like to have the "disable language extensions"  enabled when writing portable code, but it's not possible here:

1>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2001: unresolved external symbol __imp__read
1>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2001: unresolved external symbol __imp__close
1>libprotobuf.lib(zero_copy_stream_impl.obj) : error LNK2001: unresolved external symbol __imp__write

I'm using Visual Studio 2013 Update 5.

Thank you!

**Comment by xfxyjwf** [comment]
Do you mean the "read"/"write" functions used in the code?

**Comment by githubacc32** [comment]
Yea, it seems that they are non-standard and thus not available if MSVC language extensions are disabled (which they should when writing portable code I guess).

**Comment by xfxyjwf** [comment]
Could you enable these extensions when compiling protobuf (and maybe only disable them when compiling your own code)?

Protobuf code relies on these methods to read/write from/into standard io streams (STDIN_FILENO/STDOUT_FILENO). Although these methods are not in the C++ standard, code using them is still portable because all major platforms support them. There are standard alternatives for the same purpose but it will require a public API change to FileInputStream/FileOutputStream.

**Comment by githubacc32** [comment]
I am already doing this. The library builds well but the linker error occurs when I am disabling language extensions for the project that uses libprotobuf.lib.
