### ISSUE TITLE
when i compiled a proto file with a map, occer error

### ISSUE THREAD

**Issue by wanggnim** [google/protobuf#799]
use protoc-2.6.1-win32/protoc.exe

proto file :
```
message Config { 
    map<string, string> biyun_levels = 1;
}
```

error:
```
config.proto:5:5: Expected "required", "optional", or "repeated".
config.proto:5:8: Expected field name.
```

in the [doucment](https://developers.google.com/protocol-buffers/docs/proto?hl=zh-cn#other), it says protobuf2 supports Maps, but this error is why?

**Comment by xfxyjwf** [comment]
The maps syntax is only supported starting from v3.0.0. The "proto2" in the doc is referring to the syntax version, not protobuf release version. v3.0.0 supports both proto2 syntax and proto3 syntax while v2.6.1 only supports proto2 syntax. For all users, it's recommended to use v3.0.0-beta-1 instead of v2.6.1.

**Comment by LazyPlanet** [comment]
The generated map API is currently available for all proto2 supported languages. You can find out more about the map API for your chosen language in the relevant API reference.

**Comment by LazyPlanet** [comment]
does 2.6.1 support map?

**Comment by themightyoarfish** [comment]
I have 3.9.2 and still can't use any maps with the same error

> Expected field name.

With `syntax = "proto3";`

What am I doing wrong? 🤔
