### ISSUE TITLE
ObjC: Don't mangle filenames

### ISSUE THREAD

**Issue by kientzle** [google/protobuf#864]
The Obj-C backend currently mangles the input filenames, converting e.g., foo_bar.proto to FooBar.pb.m.  This causes problems for build systems (including Xcode) that could otherwise automatically track dependencies and recompile proto files only as needed.

The offending code is in src/google/protobuf/compiler/objectivec/objectivec_helpers.cc.  The call to UnderscoresToCamelCase() here should be removed:

string FilePath(const FileDescriptor\* file) {
  string output;
  string basename;
  string directory;
  PathSplit(file->name(), &directory, &basename);
  if (directory.length() > 0) {
    output = directory + "/";
  }
  basename = StripProto(basename);

  // CamelCase to be more ObjC friendly.
  basename = UnderscoresToCamelCase(basename, true);

  output += basename;
  return output;
}

**Comment by thomasvl** [comment]
I believe a few other languages do this also (java?  C#?).  Since this would be a break change for folks, I don't think we're likely to change the behavior at this point.

**Comment by kientzle** [comment]
How do you compile your Obj-C programs?  If you're using Xcode, I'd love to see the Xcode build rules you're using to recompile your protos.  Personally, I would like to use something similar to this with make:

%.objc.h %.objc.m: %.proto
   protoc ...

But that requires that the base filenames match.

**Comment by thomasvl** [comment]
Since a proto can reference another proto, you end up needing to also have the dependency change exposes to trigger rebuilds (just like source files).  So Xcode's build rule model already can't capture that.  I've seen script do it to deal with the dependency chain problem, but none of them are pretty.  Google uses http://bazel.io which knows about protos, so we don't directly have this issue.  We've talked about doing an Xcode plugin to make the build/rebuild process better, but haven't really put time into it.

**Comment by thomasvl** [comment]
fyi - You might also want to look at the --dependency_out option.  You might be able to use that to help pick off the name transform and dependency info.
