### ISSUE TITLE
Plugin: Responsibility to create directories

### ISSUE THREAD

**Issue by alexbiehl** [google/protobuf#914]
Generating code from a _CodeGeneratorRequest_ sometimes yields a path with nested subdirectories: 
`Security.proto -> SecurityProtos/...`
When a subdirectory does not exists `protoc` complains about it instead of creating it. Ideally the [`Open`](https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc#L1562) method should create parent directories too.

Or is it the responsibility of my plugin to create said directory structures? As this case seems to be not documented.

**Comment by xfxyjwf** [comment]
The GeneratorContext is shared by plugins and built-in code generators. Since the built-in code generators can generate code in subdirectories, I think plugins should be able to do that as well.

Here is the line where the GeneratorContext creates directories:
https://github.com/google/protobuf/blob/master/src/google/protobuf/compiler/command_line_interface.cc#L414

**Comment by alexbiehl** [comment]
Ah! I was on a Windows machine when I reported. Trying out the same procedure works on OSX. Maybe there is some bug in a Windows specific part of the code.

**Comment by xfxyjwf** [comment]
Could you make sure the path passed to the Open() method by the plugin are relative paths and are using "/" instead of "\" on windows?

**Comment by acozzette** [comment]
I am going to go ahead and close this because we are cleaning up issues and I see that this one has not been updated in a long time. Feel free to reopen it if this is still a problem, though.
